### ISSUE TITLE
Issue with grammar ?

### ISSUE THREAD

**Issue by leochand101** [lark-parser/lark#1014]
@MegaIng We talked about this in Gitter FYI
```
import logging
import re
from lark import Lark, logger

logger.setLevel(logging.DEBUG)

spice_grammar = r"""
    start: cellname 
    cellname: ".SUBCKT" cell~1 pinlist cellbody ".ENDS"
    cellbody: mosfet | resistor+ | cap+ | diode+ | xsub+
    // More rules with TERM I will create with identifiers
    resistor: /ex/
    cap: /ex1/
    diode: /ex2/
    xsub: /ex3/
    // 
    ?mosfet: fetname~1 mpinlist MOSNAME~1 mosparams "\n"
    MOSNAME: IDENTIFIER
    PNAME:IDENTIFIER
    fetname: /^M[a-zA-Z0-9]*/
    cell: IDENTIFIER 
    mpinlist: IDENTIFIER (IDENTIFIER)~3
    pinlist: IDENTIFIER (IDENTIFIER)* "\n"
    VALUE: /\d+.?\d*[a-z]*/
    IDENTIFIER: CNAME
    // Variation below as (IDENTIFIER VALUE) when I ignore /=/
    param: (IDENTIFIER"="VALUE)
    mosparams: param~3

    COMMENT: /\*.*/
    %ignore COMMENT

    %import common.WS
    %ignore WS
    // Variation with below ignore
    //%ignore /=/
    //%import common.WORD
    //%import common.ESCAPED_STRING
    //%import common.SIGNED_NUMBER
    %import common.CNAME
"""

test_text="""
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
* POSSIBILITY OF SUCH DAMAGE.

.SUBCKT A2O1A1Ixp33_ASAP7_75t_R A1 A2 B C VDD VSS Y
** MM7 net06 B VSS VSS nmos_rvt w=81.0n l=20n nfin=3
MM2 Y C net06 VSS nmos_rvt w=81.0n l=20n nfin=3
.ENDS
"""
#MM1 net015 A2 VSS VSS nmos_rvt w=81.0n l=20n nfin=3
#MM0 net06 A1 net015 VSS nmos_rvt w=81.0n l=20n nfin=3
#MM6 Y C VDD VDD pmos_rvt w=54.0n l=20n nfin=2
#MM5 Y B net2 VDD pmos_rvt w=81.0n l=20n nfin=3
#MM4 net2 A2 VDD VDD pmos_rvt w=81.0n l=20n nfin=3
#MM3 net2 A1 VDD VDD pmos_rvt w=81.0n l=20n nfin=3
#.ENDS
#"""
#print(re.search('.SUBCKT',test_text))
spice_lark=Lark(spice_grammar, parser='lalr',
        lexer="contextual",propagate_positions=True)
spice_lark.parse(test_text)
.
```
Overall Goal:
""" Trying to ignore comments ^*.* and then trying to parse the defintion of a
subcircuit between .SUBCKT and .ENDS , Will Parse cellname right after the
subckt and then the other portions
messages are very specific (usually regex related/lark TERMINAL matching)
NOTE: braces dont exist I am trying to show the tokens that I will need post
parse
Basically A2O1A1Ixp33_ASAP7_75t_R > 
.SUBCKT {A2O1A1Ixp33_ASAP7_75t_R} {A1 A2 B C VDD VSS Y}
{MM2} {Y C net06 VSS} {nmos_rvt} {{w=81.0n} {l=20n} {nfin=3}}
    '
    '
    '
.ENDS
"""

Stuck AT:
```
Unused terminals: ['CNAME', 'PNAME']
Traceback (most recent call last):
  File "/home/chandru/anaconda3/lib/python3.7/site-packages/lark/lexer.py", line 458, in lex
    yield lexer.next_token(lexer_state, parser_state)
  File "/home/chandru/anaconda3/lib/python3.7/site-packages/lark/lexer.py", line 380, in next_token
    state=parser_state, terminals_by_name=self.terminals_by_name)
lark.exceptions.UnexpectedCharacters: No terminal matches '=' in the current parser context, at line 7 col 29

MM2 Y C net06 VSS nmos_rvt w=81.0n l=20n nfin=3
                            ^
Expected one of: 
	* IDENTIFIER

Previous tokens: Token('IDENTIFIER', 'w')


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parse_spice.py", line 86, in <module>
    spice_lark.parse(test_text)
  File "/home/chandru/anaconda3/lib/python3.7/site-packages/lark/lark.py", line 561, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/home/chandru/anaconda3/lib/python3.7/site-packages/lark/parser_frontends.py", line 107, in parse
    return self.parser.parse(stream, start, **kw)
  File "/home/chandru/anaconda3/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 41, in parse
    return self.parser.parse(lexer, start)
  File "/home/chandru/anaconda3/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 171, in parse
    return self.parse_from_state(parser_state)
  File "/home/chandru/anaconda3/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 188, in parse_from_state
    raise e
  File "/home/chandru/anaconda3/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 178, in parse_from_state
    for token in state.lexer.lex(state):
  File "/home/chandru/anaconda3/lib/python3.7/site-packages/lark/lexer.py", line 467, in lex
    raise UnexpectedToken(token, e.allowed, state=parser_state, token_history=[last_token], terminals_by_name=self.root_lexer.terminals_by_name)
lark.exceptions.UnexpectedToken: Unexpected token Token('EQUAL', '=') at line 7, column 29.
Expected one of: 
	* NEWLINE
	* IDENTIFIER
Previous tokens: [Token('IDENTIFIER', 'w')]
```

Alternative:
I could ignore /=/ altogether but then I get stuck at:
Unused terminals: ['CNAME', 'PNAME']
Traceback (most recent call last):
  File "/home/chandru/anaconda3/lib/python3.7/site-packages/lark/lexer.py", line 458, in lex
    yield lexer.next_token(lexer_state, parser_state)
  File "/home/chandru/anaconda3/lib/python3.7/site-packages/lark/lexer.py", line 380, in next_token
    state=parser_state, terminals_by_name=self.terminals_by_name)
lark.exceptions.UnexpectedCharacters: No terminal matches '8' in the current parser context, at line 7 col 30

MM2 Y C net06 VSS nmos_rvt w=81.0n l=20n nfin=3
                             ^
Expected one of: 
	* IDENTIFIER

Previous tokens: Token('IDENTIFIER', 'w')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parse_spice.py", line 88, in <module>
    spice_lark.parse(test_text)
  File "/home/chandru/anaconda3/lib/python3.7/site-packages/lark/lark.py", line 561, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/home/chandru/anaconda3/lib/python3.7/site-packages/lark/parser_frontends.py", line 107, in parse
    return self.parser.parse(stream, start, **kw)
  File "/home/chandru/anaconda3/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 41, in parse
    return self.parser.parse(lexer, start)
  File "/home/chandru/anaconda3/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 171, in parse
    return self.parse_from_state(parser_state)
  File "/home/chandru/anaconda3/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 188, in parse_from_state
    raise e
  File "/home/chandru/anaconda3/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 178, in parse_from_state
    for token in state.lexer.lex(state):
  File "/home/chandru/anaconda3/lib/python3.7/site-packages/lark/lexer.py", line 467, in lex
    raise UnexpectedToken(token, e.allowed, state=parser_state, token_history=[last_token], terminals_by_name=self.root_lexer.terminals_by_name)
lark.exceptions.UnexpectedToken: Unexpected token Token('VALUE', '81.0n') at line 7, column 30.
Expected one of: 
	* IDENTIFIER
	* NEWLINE
Previous tokens: [Token('IDENTIFIER', 'w')]

**Comment by MegaIng** [comment]
Part of your problem is that `MM2` can match both `fetname` and `IDENTIFIER` (inside of `pinlist`). This means that the lexers might get confused which one it is. Changing that (e.g. using `IDENTIFIER` there), and switching the parser to `earley` works for me. In general, unless you have performance problems or know that your grammar is LALR compatible, `earley` is a good choice.

**Comment by leochand101** [comment]
Ohh wow, that was quick, can you explain also explain why (CNAME "=" VALUE) doesnt work in the param rule in the first case ?? Can EQUAL//=/ not be filtered and used as an anchor in rule ?

**Comment by MegaIng** [comment]
Not sure what you mean. Defacto is the problem that `MM2` is recognized as an `IDENTIFIER`, which means that there is not valid way to accept an `=` afterwards, since `fetname` is never matched.

**Comment by erezsh** [comment]
Sorry, I can't think of a good tutorial, other than the ones included in the docs. What do you mean by conceptual level?
