### ISSUE TITLE
Exception during exception unwind, KeyError/UnexpectedToken causes Python to crash (can't catch exception).

### ISSUE THREAD

**Issue by lewismj** [lark-parser/lark#1030]
**Describe the bug**

I was testing some code of mine, with invalid input, and had a catastrophic error that killed python, the trace is below.

The invalid input generated an `UnexpectedToken` which is great, but then I think there are some issues with how
that gets handled:

 `lark.exceptions.UnexpectedToken <exception str() failed>`
(Not sure if the exception str() failing is an issue).

But it seems the issue is this is thrown during `KeyError` unwind... I'll try to step through in the debugger myself.

```
Traceback (most recent call last):
  File "/Users/lewismj/opt/anaconda3/envs/eta/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 126, in feed_token
    action, arg = states[state][token.type]
KeyError: '$END'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lewismj/develop/eta/eta/repl.py", line 86, in repl
    ast = parser.parse("({})".format(text))
  File "/Users/lewismj/opt/anaconda3/envs/eta/lib/python3.7/site-packages/lark/lark.py", line 581, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/Users/lewismj/opt/anaconda3/envs/eta/lib/python3.7/site-packages/lark/parser_frontends.py", line 106, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "/Users/lewismj/opt/anaconda3/envs/eta/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 41, in parse
    return self.parser.parse(lexer, start)
  File "/Users/lewismj/opt/anaconda3/envs/eta/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 171, in parse
    return self.parse_from_state(parser_state)
  File "/Users/lewismj/opt/anaconda3/envs/eta/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 188, in parse_from_state
    raise e
  File "/Users/lewismj/opt/anaconda3/envs/eta/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 182, in parse_from_state
    return state.feed_token(end_token, True)
  File "/Users/lewismj/opt/anaconda3/envs/eta/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 129, in feed_token
    raise UnexpectedToken(token, expected, state=self, interactive_parser=None)
lark.exceptions.UnexpectedToken: <exception str() failed>
```

**To Reproduce**

I will try to cut down my code to reproduce this error, I'm posting this now as it may be a quick fix.

**Comment by MegaIng** [comment]
If this leads to an Interpreter crash (which seems unlikely) then there is nothing we can do about that.

However, the `<exception str() failed>` is very much a problem. That means that larks exception classes fail to actually generate a message and instead raise another exception during that.

What version of lark do you have?
