### ISSUE TITLE
The case containing no spaces raises an error

### ISSUE THREAD

**Issue by vaxin** [lark-parser/lark#1058]
**Lark**
```
start: CITY WORD TAIL		
CITY  : "TOKYO" | "LONDON"
TAIL : "INC"
%import common.WORD
```

test text: TOKYOaaINC

**Error**
```
PythonError: Traceback (most recent call last):
  File "/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 494, in eval_code_async
    await CodeRunner(
  File "/lib/python3.9/site-packages/_pyodide/_base.py", line 345, in run_async
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 1, in <module>
  File "/lib/python3.9/site-packages/lark/lark.py", line 581, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/lib/python3.9/site-packages/lark/parser_frontends.py", line 106, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "/lib/python3.9/site-packages/lark/parsers/earley.py", line 305, in parse
    raise UnexpectedEOF(expected_terminals, state=frozenset(i.s for i in to_scan))
lark.exceptions.UnexpectedEOF: Unexpected end-of-input. Expected one of: 
	* TAIL
```

**Comment by vaxin** [comment]
Why I construct this case, because in many language, words are not segmented by spaces like Chinese: 这是一段中文。

**Comment by MegaIng** [comment]
This is intentionally since most of the time if you deal with Programming Languages spaces signify the separations between tokens (for example in python `def ine` vs `define`, in the first case `def` is a keyword.

But this is actually only half of the explanation, since  you `CITY` pattern works. This is because in addition to the indent behavior above `WORD` is also greedy and becomes as long as possible without the parser stooping it. WORD doesn't know that `TAIL` still needs to be parsed.

For some kind of natural language processing you probably need to use `parser='earley', lexer='dynamic_complete'`. While slow, these options should allow lark to parse just about anything with a context free structure
