### ISSUE TITLE
The presence of pydot causes parse to fail when debug=True

### ISSUE THREAD

**Issue by rowlesmr** [lark-parser/lark#1121]
**Describe the bug**

I am debugging a grammar, and the corrected output was displayed with the message "Cannot find dependency 'pydot', will not generate sppf debug image". After installing pydot, the previously working parsing failed with the exception :IndexError: list index out of range

**To Reproduce**

```
from lark import Lark, logger

logger.setLevel(logging.DEBUG)  # this is necessary to get the "Cannon find..." warning
mwe = r"""
start: DIGIT+
DIGIT: /[0-9]/
"""

string = "3"
parser = Lark(mwe, debug=True)  # if this is false, the parsing succeeds with or without pydot
print(parser.parse(string).pretty())
```

Program output without pydot installed:

```
Cannot find dependency 'pydot', will not generate sppf debug image
start	3
```

Program output with pydot installed

```
Traceback (most recent call last):
  File "C:\Users\___\Documents\GitHub\___\lark_parser.py", line 163, in <module>
    print(parser.parse(string).pretty())
  File "C:\Users\___\AppData\Local\Programs\Python\Python39\lib\site-packages\lark\lark.py", line 619, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "C:\Users\___\AppData\Local\Programs\Python\Python39\lib\site-packages\lark\parser_frontends.py", line 99, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "C:\Users\___\AppData\Local\Programs\Python\Python39\lib\site-packages\lark\parsers\earley.py", line 283, in parse
    debug_walker.visit(solutions[0], "sppf.png")
  File "C:\Users\___\AppData\Local\Programs\Python\Python39\lib\site-packages\lark\parsers\earley_forest.py", line 742, in visit
    super(ForestToPyDotVisitor, self).visit(root)
  File "C:\Users\___\AppData\Local\Programs\Python\Python39\lib\site-packages\lark\parsers\earley_forest.py", line 336, in visit
    vpno(current)
  File "C:\Users\___\AppData\Local\Programs\Python\Python39\lib\site-packages\lark\parsers\earley_forest.py", line 774, in visit_packed_node_out
    child_graph_node = self.graph.get_node(child_graph_node_id)[0]
IndexError: list index out of range
```

Without pydot:
```
pip freeze
altgraph==0.17
argon2-cffi==21.1.0
argparse-formatter==1.4
arrow==1.2.1
astroid==2.6.2
atomicwrites==1.4.0
attrs==21.2.0
autopep8==1.5.5
backcall==0.2.0
binaryornot==0.4.4
bleach==4.1.0
bokeh==2.4.0
Brotli==1.0.9
bump2version==1.0.1
cefpython3==66.1
certifi==2021.10.8
cffi==1.14.6
chaco==5.0.0
chardet==4.0.0
charset-normalizer==2.0.7
-e git+https://github.com/rowlesmr/ciftostr.git@70a17a160ac9d546bd5b7b32e17b4067cd311672#egg=ciftostr
click==7.1.2
cloudpickle==1.6.0
colorama==0.4.4
colored==1.4.3
colorspacious==1.1.2
cookiecutter==1.7.3
coverage==5.5
cycler==0.11.0
Cython==0.29.24
dash==2.0.0
dash-bootstrap-components==0.13.1
dash-core-components==2.0.0
dash-daq==0.5.0
dash-html-components==2.0.0
dash-table==5.0.0
dash-uploader==0.6.0
decorator==4.4.2
defusedxml==0.7.1
DiffUtil==0.0.0
docutils==0.18
enable==5.2.1
entrypoints==0.3
flake8==3.8.4
flake8-docstrings==1.6.0
Flask==2.0.1
Flask-Compress==1.10.1
Flask-WTF==1.0.0
fonttools==4.27.1
future==0.18.2
Gooey==1.0.8.1
idna==3.3
importlib-metadata==4.8.1
importlib-resources==5.2.2
iniconfig==1.1.1
ipykernel==5.5.4
ipython==7.23.1
ipython-genutils==0.2.0
ipywidgets==7.6.5
isort==5.9.1
itsdangerous==2.0.1
jedi==0.17.2
Jinja2==3.0.1
jinja2-time==0.2.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.12
jupyter-console==6.4.0
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.2
keyring==23.2.1
kiwisolver==1.3.2
lark==1.1.1
lazy-object-proxy==1.6.0
llvmlite==0.36.0
MarkupSafe==2.0.1
matplotlib==3.4.3
matplotlib-inline==0.1.2
mccabe==0.6.1
mistune==0.8.4
mplcursors==0.5
nameparser==1.0.6
natsort==8.0.2
nbclient==0.5.4
nbconvert==6.1.0
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.4.4
numba==0.53.1
numpy==1.21.4
orjson==3.6.4
packaging==21.0
pandas==1.3.3
pandocfilters==1.5.0
parsimonious==0.8.1
parso==0.7.1
pathlib==1.0.1
-e git+https://github.com/rowlesmr/pdCIFplotter.git@b0b60e30e1b5a81bcb88f259211b73f5675d77d6#egg=pdCIFplotter
-e git+https://github.com/rowlesmr/pdiffutils.git@fea71083821e6ac997839a5a40d3a41d8fe9fcec#egg=pdiffutils
pefile==2019.4.18
pegen==0.1.0
pickleshare==0.7.5
Pillow==8.4.0
pkginfo==1.8.2
plotly==5.3.1
pluggy==0.13.1
poyo==0.5.0
prometheus-client==0.11.0
prompt-toolkit==3.0.18
psutil==5.8.0
-e git+https://github.com/rowlesmr/pvct.git@6beb83f824cccd031b20b5c683a2f9fc9e934e82#egg=pvct
py==1.10.0
PyCifRW==4.4.3
pycodestyle==2.6.0
pycparser==2.20
pydocstyle==6.1.1
pyface==7.3.0
pyflakes==2.2.0
Pygments==2.9.0
pygtrie==2.4.2
pyinstaller==4.7
pyinstaller-hooks-contrib==2021.1
pylint==2.9.3
pyopt==0.84
pyparsing==3.0.4
pyperclip==1.8.2
PyQt5==5.15.4
pyqt5-plugins==5.15.4.2.2
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.0
pyqt5-tools==5.15.4.3.2
pyqtgraph==0.12.2
PyQtWebEngine==5.15.4
PyQtWebEngine-Qt5==5.15.2
pyrsistent==0.18.0
PySide2==5.15.2
PySimpleGUI==4.55.0
PySimpleGUIQt==0.35.0
PySimpleGUIWeb==0.39.0
PySimpleGUIWx==0.17.2
pytest==6.2.4
python-dateutil==2.8.2
python-dotenv==0.18.0
python-jsonrpc-server==0.4.0
python-language-server==0.36.2
python-slugify==5.0.2
pytz==2021.1
pywin32==300
pywin32-ctypes==0.2.0
pywinpty==1.1.4
PyYAML==5.4.1
pyzmq==22.0.3
qt5-applications==5.15.2.2.2
qt5-tools==5.15.2.1.2
qtconsole==5.1.1
QtPy==1.11.1
readme-renderer==30.0
remi==2021.3.2
requests==2.26.0
requests-toolbelt==0.9.1
rfc3986==1.5.0
rope==0.19.0
scipy==1.6.3
Send2Trash==1.8.0
setuptools-scm==6.3.2
shiboken2==5.15.2
six==1.16.0
snowballstemmer==2.1.0
spyder-kernels==2.0.3
tenacity==8.0.1
terminado==0.12.1
testpath==0.5.0
text-unidecode==1.3
tkinterhtml==0.7
toml==0.10.2
tomli==2.0.0
tornado==6.1
tqdm==4.62.3
traitlets==5.0.5
traits==6.2.0
traitsui==7.2.1
twine==3.7.1
typing-extensions==3.10.0.2
ujson==4.0.2
urllib3==1.26.7
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==2.0.1
widgetsnbextension==3.5.1
wrapt==1.12.1
WTForms==3.0.1
wxmplot==0.9.45
wxPython==4.1.1
yapf==0.31.0
zipp==3.6.0
```

With pydot (pip install pydot)
```
pip freeze
as above +
pydot==1.4.2
```

**Comment by erezsh** [comment]
@night199uk Any chance you can take a look at this?

I think it should be fine to just skip `add_edge()` if the list is empty, but maybe this is a symptom of a hidden bug?

**Comment by xor2003** [comment]
Same for me:
build==0.8.0
click==7.1.2
distlib==0.3.5
filelock==3.7.1
gevent==21.12.0
greenlet==1.1.2
jsonpickle==2.2.0
lark==1.1.2
packaging==21.3
parglare==0.15.0
pbr==5.9.0
pep517==0.12.0
platformdirs==2.5.2
plumbum @ git+https://github.com/tomerfiliba/plumbum.git@70380ddc5ad346ab6758506f5000864260a9c418
pydot==1.4.2
pyparsing==3.0.9
rangeslicetools @ git+https://github.com/KOLANICH-libs/rangeslicetools.py.git@3111219b6ee52556483e5e6e260ba769b14e818b
six==1.16.0
stevedore==4.0.0
stringcase @ git+https://github.com/okunishinishi/python-stringcase.git@04afe0044a9c513bc7899ae2dd1b97f1fe165f6c
tomli==2.0.1
virtualenv==20.15.1
virtualenv-clone==0.5.7
virtualenvwrapper==4.8.4
zope.event==4.5.0
zope.interface==5.4.0

**Comment by erezsh** [comment]
Alright, unless someone wants to take it on himself to fix it, I'll just comment out the automatic pydot.

**Comment by chanicpanic** [comment]
I bisected it to afcde7c9. I will look into it. The issue may have something to do with the introduction of `TokenNode`.

**Comment by erezsh** [comment]
@rowlesmr @xor2003 Can you please verify this PR fixes your issue?

```
pip install git+https://github.com/lark-parser/lark.git@refs/pull/1167/head
```

**Comment by xor2003** [comment]
Thanks. The exception is not happening for me anymore
