### ISSUE TITLE
GrammarError when rule definition contains TERM?rule

### ISSUE THREAD

**Issue by chanicpanic** [lark-parser/lark#1172]
**Describe the bug**

Lark raises a `GrammarError` when the provided grammar contains a rule of the form `name: TERM?rule`. 

I expect `name: TERM?rule` to be valid lark syntax and be parsed equivalently to `name: TERM? rule`.

**To Reproduce**

```
>>> Lark('start: "A"?b\nb:')
Traceback (most recent call last):
  File "/__/lark/parsers/lalr_parser.py", line 125, in feed_token
    action, arg = states[state][token.type]
KeyError: 'RULE_MODIFIERS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/__/lark/load_grammar.py", line 961, in _parse_grammar
    tree = _get_parser().parse(text + '\n', start)
  File "/__/lark/parser_frontends.py", line 96, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "/__/lark/parsers/lalr_parser.py", line 40, in parse
    return self.parser.parse(lexer, start)
  File "/__/lark/parsers/lalr_parser.py", line 170, in parse
    return self.parse_from_state(parser_state)
  File "/__/lark/parsers/lalr_parser.py", line 187, in parse_from_state
    raise e
  File "/__/lark/parsers/lalr_parser.py", line 178, in parse_from_state
    state.feed_token(token)
  File "/__/lark/parsers/lalr_parser.py", line 128, in feed_token
    raise UnexpectedToken(token, expected, state=self, interactive_parser=None)
lark.exceptions.UnexpectedToken: Unexpected token Token('RULE_MODIFIERS', '?') at line 1, column 11.
Expected one of:
        * _LPAR
        * _NL_OR
        * _NL
        * STRING
        * OP
        * _OR
        * REGEXP
        * _TO
        * _DOTDOT
        * _LBRA
        * RULE
        * TERMINAL
        * TILDE


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/__/lark/lark.py", line 336, in __init__
    self.grammar, used_files = load_grammar(grammar, self.source_path, self.options.import_paths, self.options.keep_all_tokens)
  File "/__/lark/load_grammar.py", line 1408, in load_grammar
    builder.load_grammar(grammar, source)
  File "/__/lark/load_grammar.py", line 1233, in load_grammar
    tree = _parse_grammar(grammar_text, grammar_name)
  File "/__/lark/load_grammar.py", line 970, in _parse_grammar
    raise GrammarError("%s, at line %s column %s\n\n%s" % (error, e.line, e.column, context))
lark.exceptions.GrammarError: Unexpected colon, at line 1 column 11

start: "A"?b
          ^
```

From my experiments, it looks like removing the lookahead from the `OP` terminal and changing the grammar parser's lexer to `'contextual'` fixes the issue. However, I am not sure if that will have any undesired side effects or if there is a better approach.

**Comment by erezsh** [comment]
It seems like you're getting the wrong error message.. but you should be getting an error.

This should be written as 

```lark
start: "A"? b
```

Without the space, it's not legal syntax.

**Comment by chanicpanic** [comment]
Could `start: "A"?b` (without the space) be made legal syntax?

I am wondering because I was playing around with the reconstructor with `lark.lark` and a pattern of the form `"A"?b` was in the reconstructed grammar. Lark could not parse the reconstructed grammar, but it looks like it could be parsed unambiguously.

**Comment by erezsh** [comment]
If you're generating Lark grammars, Why not always add a space between the elements? I think it could work.

**Comment by chanicpanic** [comment]
> If you're generating Lark grammars, Why not always add a space between the elements? I think it could work.

Good idea. I inserted the necessary space by passing the following postproc to `reconstruct`:

```python
def postproc(strings):
    prev = ""
    for item in strings:
        if prev and prev[-1] == "?" and isinstance(item, Token) and item.type == "RULE":
            yield " "
        yield item
        prev = item
```

**Comment by erezsh** [comment]
I would have gone with something a bit simpler, but I guess its output is less neat.

```
def postproc(strings):
    for item in strings:
        if item.endswith("?") :
            yield " "
        yield item
```
