### ISSUE TITLE
Saving Earley parser doesn't work

### ISSUE THREAD

**Issue by ivkovicdjordje** [lark-parser/lark#1323]
**Describe the bug**

Saving Earley parser with `parser.save(file)` throws `TypeError: cannot pickle 'module' object`.

**To Reproduce**

```python
from lark.lark import Lark
grammar = """
hello_world: HELLO_TOKEN " " WORLD_TOKEN "."
HELLO_TOKEN: "hello"
WORLD_TOKEN: "world"
"""
parser = Lark(grammar, start="hello_world", parser="earley")
print(parser.parse("hello world."))


with open("parser.pkl", "wb") as file:
    parser.save(file)
```

Logs:
```
Tree(Token('RULE', 'hello_world'), [Token('HELLO_TOKEN', 'hello'), Token('WORLD_TOKEN', 'world')])
Traceback (most recent call last):
  File "/home/djiv/dev/examples/lark_pickle/src/save_lark.py", line 13, in <module>
    parser.save(file)
  File "/home/djiv/dev/examples/lark_pickle/venv/lib/python3.10/site-packages/lark/lark.py", line 500, in save
    pickle.dump({'data': data, 'memo': m}, f, protocol=pickle.HIGHEST_PROTOCOL)
TypeError: cannot pickle 'module' object
```

Lark version used is 1.1.7

**Comment by erezsh** [comment]
The save method doesn't work for Earley.

But we need a better error for that.

**Comment by ivkovicdjordje** [comment]
Can you explain why save method doesn't work for Earley?

**Comment by erezsh** [comment]
I just never implemented it.

See issue #788

**Comment by erezsh** [comment]
But if anyone wants to contribute a PR for it, they are more than welcome.
