### ISSUE TITLE
GrammarError: Rule 'anycase' used but not defined (in rule pipesyn)

### ISSUE THREAD

**Issue by RossPatterson** [lark-parser/lark#1355]
When attempting to load a small grammar, Lark reports that a rule alias name is "used but not defined".  It's rather obviously defined, as the only usage of the name is the alias.  The specific alias that gets flagged varies - running the example below flags `anycase`, `anyof`, and `mask`, seemingly randomly.

The grammar is intended to recognize simple operand strings like:

```
AnYcA mIXEd

ONEs

zero ANYOF
```

To reproduce, run the following:

```python
import lark

grammar = '''
start: pipesyn
pipesyn: ["any"i ("c"i ("a"i ("s"i ("e"i)? )? )? )? -> anycase]
 | [("mixed"i
 | "one"i ("s"i)?
 | "zero"i ("s"i)?) -> mask]
 | ["anyo"i ("f"i)? -> anyof]
'''

parser = lark.Lark(grammar, parser="lalr")
```

You'll get an exception like the following:
```
(.venv) C:\Ross\Source\Pype>py src\pype\issue.py
Traceback (most recent call last):
  File "C:\Ross\Source\Pype\src\pype\issue.py", line 12, in <module>
    parser = lark.Lark(grammar, parser="lalr")
  File "C:\Ross\Source\Pype\.venv\lib\site-packages\lark\lark.py", line 356, in __init__
    self.grammar, used_files = load_grammar(grammar, self.source_path, self.options.import_paths, self.options.keep_all_tokens)
  File "C:\Ross\Source\Pype\.venv\lib\site-packages\lark\load_grammar.py", line 1411, in load_grammar
    return builder.build(), builder.used_files
  File "C:\Ross\Source\Pype\.venv\lib\site-packages\lark\load_grammar.py", line 1370, in build
    self.validate()
  File "C:\Ross\Source\Pype\.venv\lib\site-packages\lark\load_grammar.py", line 1364, in validate
    self._grammar_error(d.is_term, "{Type} '{name}' used but not defined (in {type2} {name2})", sym, name)
  File "C:\Ross\Source\Pype\.venv\lib\site-packages\lark\load_grammar.py", line 1104, in _grammar_error
    raise GrammarError(msg.format(**args))
lark.exceptions.GrammarError: Rule 'anycase' used but not defined (in rule pipesyn)
```

**Comment by MegaIng** [comment]
Nesting aliases inside of other constructs is not supported, and honestly should be throwing errors way earlier. Aliases should always be top level in a rule definition I am not even sure what you want do with all the `[]` pairs, but those are causing problems here.

**Comment by RossPatterson** [comment]
> Nesting aliases inside of other constructs is not supported, and honestly should be throwing errors way earlier.

I can see why that would be (I've hand-coded parsers many times), but I should point out that the Lark documentation doesn't even imply that, and this grammar parses successfully with the `grammars/lark.lark` parser:

```
import lark

grammar = '''
start: pipesyn
pipesyn: ["any"i ("c"i ("a"i ("s"i ("e"i)? )? )? )? -> anycase]
 | [("mixed"i
 | "one"i ("s"i)?
 | "zero"i ("s"i)?) -> mask]
 | ["anyo"i ("f"i)? -> anyof]
'''

parser = lark.Lark(open("C:/Ross/Source/Pype/.venv/Lib/site-packages/lark/grammars/lark.lark"), parser="lalr")

parse_tree = parser.parse(grammar)

print(parse_tree.pretty())
```

yields:

```
start
  rule
    start
    rule_params	None
    alias
      expr
        name	pipesyn
        None
        None
      None
  rule
    pipesyn
    rule_params	None
    expansions
      alias
        expr
          maybe
            alias
              expansion
                expr
                  literal	"any"i
                  None
                  None
                expr
                  alias
                    expansion
                      expr
                        literal	"c"i
                        None
                        None
... much elided ...
      alias
        expr
          maybe
            alias
              expansion
                expr
                  literal	"anyo"i
                  None
                  None
                expr
                  alias
                    expr
                      literal	"f"i
                      None
                      None
                    None
                  ?
              anyof
          None
          None
        None
```

**Comment by MegaIng** [comment]
Yes, it *parses* successfully, but aliases then break or get ignored in the post processing. This has been on my radar for some time, but you are actually the first person I remember running into this issue so it's low priority.

**Comment by RossPatterson** [comment]
> Yes, it *parses* successfully, but aliases then break or get ignored in the post processing. 

Got it.

> so it's low priority.

Agreed.  I'll change my use of Lark to not do this, and I'll probably work up a documentation PR to clarify the use of rule aliases.

**Comment by RossPatterson** [comment]
Closing this, as the error was mine, not Lark's.  I'll pursue the PR separately.
