### ISSUE TITLE
parsing.py example - lark.exceptions.GrammarError

### ISSUE THREAD

**Issue by 7flash** [lark-parser/lark#1389]
**To Reproduce**

```
python3 ./outlines/examples/parsing.py
```

shows an error

```
/Users/gur/miniconda3/envs/jan25/lib/python3.10/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "/Users/gur/Documents/jan18/./outlines/examples/parsing.py", line 22, in <module>
    parser = PartialLark.open_from_package(
  File "/Users/gur/miniconda3/envs/jan25/lib/python3.10/site-packages/lark/lark.py", line 598, in open_from_package
    return cls(text, **options)
  File "/Users/gur/miniconda3/envs/jan25/lib/python3.10/site-packages/outlines/fsm/parsing.py", line 96, in __init__
    super().__init__(grammar, **options)
  File "/Users/gur/miniconda3/envs/jan25/lib/python3.10/site-packages/lark/lark.py", line 442, in __init__
    self.parser = self._build_parser()
  File "/Users/gur/miniconda3/envs/jan25/lib/python3.10/site-packages/outlines/fsm/parsing.py", line 129, in _build_parser
    return PartialParsingFrontend(lexer_conf, parser_conf, self.options)
  File "/Users/gur/miniconda3/envs/jan25/lib/python3.10/site-packages/outlines/fsm/parsing.py", line 170, in __init__
    super().__init__(lexer_conf, parser_conf, options, parser=parser)
  File "/Users/gur/miniconda3/envs/jan25/lib/python3.10/site-packages/lark/parser_frontends.py", line 61, in __init__
    self.parser = create_parser(lexer_conf, parser_conf, options)
  File "/Users/gur/miniconda3/envs/jan25/lib/python3.10/site-packages/lark/parser_frontends.py", line 161, in create_lalr_parser
    return cls(parser_conf, debug=debug, strict=strict)
  File "/Users/gur/miniconda3/envs/jan25/lib/python3.10/site-packages/outlines/fsm/parsing.py", line 286, in __init__
    analysis = LALR_Analyzer(
  File "/Users/gur/miniconda3/envs/jan25/lib/python3.10/site-packages/lark/parsers/lalr_analysis.py", line 158, in __init__
    GrammarAnalyzer.__init__(self, parser_conf, debug, strict)
  File "/Users/gur/miniconda3/envs/jan25/lib/python3.10/site-packages/lark/parsers/grammar_analysis.py", line 158, in __init__
    raise GrammarError("Using an undefined rule: %s" % sym)
lark.exceptions.GrammarError: Using an undefined rule: NonTerminal('file_input')
```

**Comment by erezsh** [comment]
What is outlines? Why do you think it's an issue in Lark?

Closing until these questions are clarified.
