### ISSUE TITLE
test_nearley failure 

### ISSUE THREAD

**Issue by Apteryks** [lark-parser/lark#1496]
**Describe the bug**

When I run the test suite via unittest, I see:

```

======================================================================
ERROR: tests.test_nearley.test_nearley (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_nearley.test_nearley
Traceback (most recent call last):
  File "/gnu/store/jjcka1g6sk2cvwx8nm4fdwpdq3vll0v0-python-3.10.7/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/gnu/store/jjcka1g6sk2cvwx8nm4fdwpdq3vll0v0-python-3.10.7/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/tmp/guix-build-python-lark-1.2.2.drv-0/lark-1.2.2/tests/test_nearley/test_nearley.py", line 20, in <module>
    raise ImportError("Skipping Nearley tests!")
ImportError: Skipping Nearley tests!


----------------------------------------------------------------------
Ran 1116 tests in 3.867s

FAILED (errors=1, skipped=131)
```

The command I use to run the tests is:
```
python -m unittest -v
```

**To Reproduce**

In an environment having Python 3.10.7 and Setuptools 75.6.0, run the test suite with `python -m unittest -v`.

Note: The set suite succeeds when using pytest (as pytest, not python -m pytest, so probably maybe something to do with adding '.' to PYTHONPATH).

**Comment by erezsh** [comment]
You should not be using unitest.

There are many ways to run the tests, but I prefer one of these two:

- python -m tests
- pytest

You can also use tox
