### ISSUE TITLE
How to break a big continuous line?

### ISSUE THREAD

**Issue by evandrocoan** [lark-parser/lark#166]
I have this line on my grammar:
```regex
        productions : new_line* ( space* non_terminal_start space* "->" space* non_terminals space* end_symbol )* space* non_terminal_start space* "->" space* non_terminals space* end_symbol?
```
I would like to break it like this:
```regex
        productions : new_line* ( space* non_terminal_start space* "->" space* non_terminals space* end_symbol )* 
                      space* non_terminal_start space* "->" space* non_terminals space* end_symbol?
```
But the lark does not like it when I try to run it:
```
Traceback (most recent call last):
  File "F:\Python\lib\site-packages\lark\parsers\lalr_parser.py", line 46, in get_action
    return states[state][key]
KeyError: 'OP'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "unit_tests.py", line 7, in <module>
    from source.grammar import ChomskyGrammar
  File "D:\grammar.py", line 21, in <module>
    class ChomskyGrammar():
  File "D:\grammar.py", line 67, in ChomskyGrammar
    """, start='productions' )
  File "F:\Python\lib\site-packages\lark\lark.py", line 153, in __init__
    self.grammar = load_grammar(grammar, source)
  File "F:\Python\lib\site-packages\lark\load_grammar.py", line 599, in load_grammar
    tree = self.canonize_tree.transform( self.parser.parse(grammar_text+'\n') )
  File "F:\Python\lib\site-packages\lark\parser_frontends.py", line 37, in parse
    return self.parser.parse(token_stream)
  File "F:\Python\lib\site-packages\lark\parsers\lalr_parser.py", line 71, in parse
    action, arg = get_action(token.type)
  File "F:\Python\lib\site-packages\lark\parsers\lalr_parser.py", line 50, in get_action
    raise UnexpectedToken(token, expected, seq, i)
lark.common.UnexpectedToken: Unexpected token Token(OP, '*') at line 3, column 29.
Expected: dict_keys(['_COLON', '_DOT'])
Context: <no context>
```
I tried to put "\\" (backslash) at the end of the first line, but still the same.

It work fine if I do not break the line and keep it like this:
```regex
        productions : new_line* ( space* non_terminal_start space* "->" space* non_terminals space* end_symbol )* space* non_terminal_start space* "->" space* non_terminals space* end_symbol?
```

**Comment by erezsh** [comment]
You're right, the syntax currently doesn't support it. I recommend that you write it differently anyway:

```python
    productions : new_line* ( nts_space "->" nt_space end_symbol )* nts_space "->" nt_space end_symbol?
    nt_space: space* non_terminals space*
    nts_space: space* non_terminal_start space*
```

**Comment by erezsh** [comment]
Also, it's better to use `%ignore SPACE` instead of adding it all over the grammar, both for readability and performance.

**Comment by evandrocoan** [comment]
I was using `%ignore SPACE` but one of my productions need to match an space explicitly:
```regex
production    : ( ( epsilon | terminal | non_terminal )+ space+ )*
```
So my tree should look like this for the input expression `S -> S SS`:
```
production
  non_terminal  S
  non_terminal
    S
    S
production
  epsilon
```
But it does not work like this when I use `%ignore SPACE`. My tree most times look like this for the input expression `S -> S SS`:
```
production
  non_terminal
    S
    S
    S
production
  epsilon
```

**Comment by erezsh** [comment]
When using dynamic Earley (which is the default algorithm), you can `%ignore SPACE` and still use `SPACE` terminals explicitly when you need to.

**Comment by evandrocoan** [comment]
It seems to not be working. This is my full grammar with ignore spaces:
```regex
    _parser = lark.Lark( r"""
        productions   : new_line* ( non_terminal_start "->" non_terminals end_symbol )* non_terminal_start "->" non_terminals end_symbol?
        non_terminals : production ( "|" production )*
        production    : ( ( epsilon | terminal | non_terminal )+ space+ )* ( epsilon | terminal | non_terminal )+
        // Forces them to appear in the tree as branches
        epsilon         : [] | "&"+
        end_symbol      : ";"* new_line new_line*
        terminal        : ( SIGNED_NUMBER | LCASE_LETTER | dash_phi_hyphen )+
        non_terminal    : UCASE_LETTER+ ( UCASE_LETTER | DIGIT | quote )*
        new_line        : NEWLINE
        quote           : "'"
        dash_phi_hyphen : "-"
        space           : " "

        // Rename the start symbol, so when parsing the tree it is simple to find it
        non_terminal_start : non_terminal

        // Import common definitions
        %import common.INT
        %import common.DIGIT
        %import common.UCASE_LETTER
        %import common.LCASE_LETTER
        %import common.SIGNED_NUMBER
        %import common.NEWLINE
        %import common.WS_INLINE

        // Set to ignore white spaces
        %ignore WS_INLINE
    """, start='productions' )
```

Parsing `S -> & | SS SSS` results wrongly in `S -> & | SSSSS`.

This is my grammar with spaces well defined (without ignore spaces):
```regex
    _parser = lark.Lark( r"""
        productions   : new_line* ( space* non_terminal_start space* "->" space* non_terminals space* end_symbol )* space* non_terminal_start space* "->" space* non_terminals space* end_symbol?
        non_terminals : production ( "|" production )*
        production    : space* ( ( epsilon | terminal | non_terminal )+ space+ )* ( epsilon | terminal | non_terminal )+ space*

        // Forces them to appear in the tree as branches
        epsilon         : [] | "&"+
        end_symbol      : ";"* space* new_line ( new_line | space )*
        terminal        : ( SIGNED_NUMBER | LCASE_LETTER | dash_phi_hyphen )+
        non_terminal    : UCASE_LETTER+ ( UCASE_LETTER | DIGIT | quote )*
        new_line        : NEWLINE
        quote           : "'"
        dash_phi_hyphen : "-"
        space           : " "

        // Rename the start symbol, so when parsing the tree it is simple to find it
        non_terminal_start : non_terminal

        // Import common definitions
        %import common.INT
        %import common.DIGIT
        %import common.UCASE_LETTER
        %import common.LCASE_LETTER
        %import common.SIGNED_NUMBER
        %import common.NEWLINE
        %import common.WS_INLINE

        // Set to ignore white spaces
        // %ignore WS_INLINE
    """, start='productions' )
```

Parsing `S -> & | SS SSS` results correctly in `S -> & | SS SSS`.

**Comment by erezsh** [comment]
The thing is, both `S -> & | SS SSS` and `S -> & | SSSSS` are legal parses in your grammar. The second version chooses the "correct" parse due to a chance of how the weighting works. It might not hold if you make too many changes to the grammar.

If it works for you, that's fine. But what I would do, is either

1) Specify the correct amounts / ratio in the grammar (just so you're away, there is the `~` operator)

2) Use `ambiguity="explicit"` and choose the right derivation myself.

**Comment by evandrocoan** [comment]
I used ambiguity, but the output have no _ambig node for the input `S -> S SS | &`:
```regex
+ productions
+   new_line
+ 
+   non_terminal_start
+     non_terminal  S
+   non_terminals
+     production
+       non_terminal
+         S
+         S
+         S
+     production
+       epsilon
+   end_symbol
+     new_line
```

Grammar:
```regex
    _parser = lark.Lark( r"""
        productions   : new_line* ( non_terminal_start "->" non_terminals end_symbol )* non_terminal_start "->" non_terminals end_symbol?
        non_terminals : production ( "|" production )*
        production    : ( ( epsilon | terminal | non_terminal )+ space+ )* ( epsilon | terminal | non_terminal )+

        // Forces them to appear in the tree as branches
        epsilon         : [] | "&"+
        end_symbol      : ";"* new_line+
        terminal        : ( SIGNED_NUMBER | LCASE_LETTER | dash_phi_hyphen )+
        non_terminal    : UCASE_LETTER+ ( UCASE_LETTER | DIGIT | quote )*
        new_line        : NEWLINE
        quote           : "'"
        dash_phi_hyphen : "-"
        space           : " "

        // Rename the start symbol, so when parsing the tree it is simple to find it
        non_terminal_start : non_terminal

        // Tells the tree-builder to inline this branch if it has only one member
        ?non_terminal_epsilon : non_terminal | epsilon

        // Stops Lark from automatically filtering out these literals from the tree
        null   : "null"
        true   : "true"
        false  : "false"

        // Import common definitions
        %import common.INT
        %import common.DIGIT
        %import common.UCASE_LETTER
        %import common.LCASE_LETTER
        %import common.SIGNED_NUMBER
        %import common.NEWLINE
        %import common.WS_INLINE

        // Set to ignore white spaces
        %ignore WS_INLINE
    """, start='productions', parser='earley', ambiguity="explicit" )
```

**Comment by evandrocoan** [comment]
Ignore the last message. Running it the example outside the application showed an ambiguous tree:
```regex
_ambig
  productions
    non_terminal_start
      non_terminal  S
    non_terminals
      production
        non_terminal
          __anon_plus_9 S
          __anon_star_10
            S
            S
      production
        epsilon &
  productions
    non_terminal_start
      non_terminal  S
    non_terminals
      production
        non_terminal
          __anon_plus_9 S
          __anon_star_10
            S
            S
      production
        epsilon
        epsilon
  productions
    non_terminal_start
      non_terminal  S
    non_terminals
      production
        non_terminal
          __anon_plus_9 S
          __anon_star_10
            S
            S
      production
        epsilon
        space    
        epsilon &
  productions
    non_terminal_start
      non_terminal  S
    non_terminals
      production
        non_terminal
          __anon_plus_9 S
          __anon_star_10
            S
            S
      production
        epsilon
        space    
        epsilon
        epsilon
  productions
    non_terminal_start
      non_terminal  S
    non_terminals
      production
        non_terminal
          __anon_plus_9 S
          __anon_star_10
            S
            S
      production
        epsilon &
        epsilon
  productions
    non_terminal_start
      non_terminal  S
    non_terminals
      production
        non_terminal
          __anon_plus_9 S
          __anon_star_10
            S
            S
      production
        epsilon
        space    
        epsilon &
        epsilon
```

**Comment by evandrocoan** [comment]
I managed to nail down the ambiguity to this minimal example:
```python
#! /usr/bin/env python
# -*- coding: utf-8 -*-

import lark

_parser = lark.Lark( r"""
    productions   : new_line* non_terminal_start "->" non_terminals end_symbol?
    non_terminals : production
    production    : ( ( epsilon | terminal | non_terminal )+ space )+

    epsilon         : "&"
    end_symbol      : new_line
    terminal        : LCASE_LETTER
    non_terminal    : UCASE_LETTER
    new_line        : NEWLINE
    quote           : "'"
    dash_phi_hyphen : "-"
    space           : " "

    non_terminal_start : non_terminal

    %import common.UCASE_LETTER
    %import common.LCASE_LETTER
    %import common.NEWLINE
    %import common.WS_INLINE
    %ignore WS_INLINE
""", start='productions', parser='earley', ambiguity="explicit" )

tree = _parser.parse( "S -> S S " )
print( tree.pretty() )
```

Changing the line:
```regex
production    : ( ( epsilon | terminal | non_terminal )+ space )+
```
To:
```regex
production    : ( ( epsilon | terminal | non_terminal )+ space )
```

Solves the ambiguity. If I understand correctly, the ambiguity is caused by the white space. Then, the only way to fix it, is not to ignore the whitespaces?

**Comment by nchammas** [comment]
> You're right, the syntax currently doesn't support it.

Is this still true? It seems that in lark 1.1.8 backslashes do allow you to break up a long line, but I'm not sure.

This is valid, for example:

```lark
filter_condition: \
    "start" "(" DATE_STRING ")" -> start
    | "end" "(" DATE_STRING ")" -> end
```

But not this:

```lark
filter_condition: \
    // a comment here messes things up
    "start" "(" DATE_STRING ")" -> start
    | "end" "(" DATE_STRING ")" -> end
```

This might be unintentional behavior because I don't see documentation for it.

**Comment by evandrocoan** [comment]
> > You're right, the syntax currently doesn't support it.
> 
> Is this still true? It seems that in lark 1.1.8 backslashes do allow you to break up a long line, but I'm not sure.

I think so. I was trying to break a lengthy statement while you broke it at the `|` operator in your example.

> But not this:
> ```lark
> filter_condition: \
>     // a comment here messes things up
>     "start" "(" DATE_STRING ")" -> start
>     | "end" "(" DATE_STRING ")" -> end
> ```

Adding a backlash at the end of the comment should work. At least this is how you do it in one-line commands break across multiple lines in Linux bash scripting:
```lark
filter_condition: \
    // a comment here messes things up \
    "start" "(" DATE_STRING ")" -> start
    | "end" "(" DATE_STRING ")" -> end
```

**Comment by nchammas** [comment]
Adding a backslash to the end of the comment doesn't seem to do anything. It seems that the backslash is a very crude line continuation "instruction" (dunno if I have the terminology correct), so this:

```lark
filter_condition: \
    // a comment here messes things up \
    "start" "(" DATE_STRING ")" -> start
    | "end" "(" DATE_STRING ")" -> end
```

Gets translated to this:

```lark
filter_condition: // a comment here messes things up
    "start" "(" DATE_STRING ")" -> start
    | "end" "(" DATE_STRING ")" -> end
```

Which is equivalent to this:

```lark
filter_condition:
    "start" "(" DATE_STRING ")" -> start
    | "end" "(" DATE_STRING ")" -> end
```

Which is invalid. 😄

I tested this locally and all three versions yield similar errors.
