### ISSUE TITLE
Lark.open(file_path) not working for UTF-8 files

### ISSUE THREAD

**Issue by evandrocoan** [lark-parser/lark#179]
I can open the file `parser.lark`:
```regex
grammar : /[a-zØ-öø-ÿ]/
``` 

Like this:
```python
#! /usr/bin/env python
# -*- coding: utf-8 -*-

import lark
grammar_file_path = "parser.lark"

with open( grammar_file_path, "r", encoding='utf-8' ) as file:
    _parser = lark.Lark( file.read(), start='grammar', parser='lalr' )
```

But with `Lark.open()`, no good:
```python
#! /usr/bin/env python
# -*- coding: utf-8 -*-

import lark
grammar_file_path = "parser.lark"
_parser = lark.Lark.open( "parser.lark", start='grammar', parser='lalr' )
```

-->
<details>
<p>

```
Traceback (most recent call last):
  File "d:\lark-parser\lark\lexer.py", line 221, in __init__
    lexer = lexer_by_tokens[key]
KeyError: frozenset({Token(TERMINAL, '__ANON_0'), 'grammar'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\lark-parser\lark\lexer.py", line 179, in __init__
    re.compile(t.pattern.to_regexp())
  File "F:\Python\lib\re.py", line 233, in compile
    return _compile(pattern, flags)
  File "F:\Python\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "F:\Python\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "F:\Python\lib\sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "F:\Python\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "F:\Python\lib\sre_parse.py", line 553, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
sre_constants.error: bad character range ˜-Ã at position 5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\no_ambiguous.py", line 11, in <module>
    _parser = lark.Lark.open( "parser.lark", start='grammar', parser='lalr' )
  File "d:\lark-parser\lark\lark.py", line 206, in open
    return cls(f, **options)
  File "d:\lark-parser\lark\lark.py", line 165, in __init__
    self.parser = self._build_parser()
  File "d:\lark-parser\lark\lark.py", line 188, in _build_parser
    return self.parser_class(self.lexer_conf, parser_conf, options=self.options)
  File "d:\lark-parser\lark\parser_frontends.py", line 46, in __init__
    self.init_contextual_lexer(lexer_conf, parser_conf)
  File "d:\lark-parser\lark\parser_frontends.py", line 23, in init_contextual_lexer
    user_callbacks=lexer_conf.callbacks)
  File "d:\lark-parser\lark\lexer.py", line 225, in __init__
    lexer = Lexer(state_tokens, ignore=ignore, user_callbacks=user_callbacks)
  File "d:\lark-parser\lark\lexer.py", line 181, in __init__
    raise LexError("Cannot compile token %s: %s" % (t.name, t.pattern))
NameError: name 'LexError' is not defined
```
</p>
</details><br>

Perhaps a encoding parameter for `Lark.open(file_path)` would do the job?

**Comment by erezsh** [comment]
Thanks for the report. I will fix this promptly.

**Comment by evandrocoan** [comment]
I would add a default parameter with `encoding='utf8'` for the open function. But you can also force everybody to use UTF8 files.

**Comment by erezsh** [comment]
It wouldn't be a bad call, but I think adding that parameter will just add code and not provide much value. After all, utf8 is fairly standard. and Lark.open is just a shortcut. If anyone has a file with an unusual encoding, they can just do `Lark(open(...), ...)`
