### ISSUE TITLE
Recursion depth exceed with rules that use themselves

### ISSUE THREAD

**Issue by adamdusty** [lark-parser/lark#186]
When I try to reference a rule in itself, I get a `RecursionError`. If I comment out `EXPR OPERATOR EXPR`, everything compiles fine. I saw a similar issue recently raised here, but it didn't seem to be quite the same. My grammar is very small and only a couple rules.

My code
```python
from lark import Lark

with open("grammar.lark") as f:
    gram = f.read()

parser = Lark(gram)
```
My grammar
```
start: EXPR+

NUMBER: SIGNED_NUMBER
IDENTIFEIR: /[_A-z]([\._A-z0-9])*/

EXPR    : NUMBER
        | IDENTIFEIR
        | EXPR OPERATOR EXPR

OPERATOR    : "+"
            | "-"
            | "*"
            | "/"
            | "%"
            | "^"


COMMENT: /#[^\n]*/
%import common.ESCAPED_STRING
%import common.SIGNED_NUMBER
%import common.WS
%ignore COMMENT
%ignore WS
```

```
Traceback (most recent call last):
  File ".\debug.py", line 8, in <module>
    parser = Lark(gram)
  File "C:\Users\adusty\DevProjects\python_env\lib\site-packages\lark\lark.py", line 160, in __init__
    tokens, self.rules, self.ignore_tokens = self.grammar.compile()
  File "C:\Users\adusty\DevProjects\python_env\lib\site-packages\lark\load_grammar.py", line 457, in compile
    for name, (token_tree, priority) in token_defs if token_tree]
  File "C:\Users\adusty\DevProjects\python_env\lib\site-packages\lark\load_grammar.py", line 457, in <listcomp>
    for name, (token_tree, priority) in token_defs if token_tree]
  File "C:\Users\adusty\DevProjects\python_env\lib\site-packages\lark\visitors.py", line 87, in transform
    tree = t.transform(tree)
  File "C:\Users\adusty\DevProjects\python_env\lib\site-packages\lark\visitors.py", line 48, in transform
    return self._transform_tree(tree)
  File "C:\Users\adusty\DevProjects\python_env\lib\site-packages\lark\visitors.py", line 44, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "C:\Users\adusty\DevProjects\python_env\lib\site-packages\lark\visitors.py", line 39, in _transform_children
    yield self._transform_tree(c) if isinstance(c, Tree) else c
  File "C:\Users\adusty\DevProjects\python_env\lib\site-packages\lark\visitors.py", line 44, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "C:\Users\adusty\DevProjects\python_env\lib\site-packages\lark\visitors.py", line 39, in _transform_children
....
  File "C:\Users\adusty\DevProjects\python_env\lib\site-packages\lark\visitors.py", line 44, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "C:\Users\adusty\DevProjects\python_env\lib\site-packages\lark\visitors.py", line 39, in _transform_children
    yield self._transform_tree(c) if isinstance(c, Tree) else c
  File "C:\Users\adusty\DevProjects\python_env\lib\site-packages\lark\visitors.py", line 44, in _transform_tree
    children = list(self._transform_children(tree.children))
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by erezsh** [comment]
You are defining terminals, not rules, and terminals shouldn't contain themselves.

Try this

```ruby
start: expr+

NUMBER: SIGNED_NUMBER
IDENTIFEIR: /[_A-z]([\._A-z0-9])*/

expr   : NUMBER
        | IDENTIFEIR
        | expr OPERATOR expr

OPERATOR    : "+"
            | "-"
            | "*"
            | "/"
            | "%"
            | "^"


COMMENT: /#[^\n]*/
%import common.ESCAPED_STRING
%import common.SIGNED_NUMBER
%import common.WS
%ignore COMMENT
%ignore WS
```

I suggest you look at the calculator example, which does exactly that: https://github.com/lark-parser/lark/blob/master/examples/calc.py

**Comment by adamdusty** [comment]
Wow, that was silly of me. Thank you.
