### ISSUE TITLE
AttributeError when it catches UnexpectedCharacters

### ISSUE THREAD

**Issue by rnarkk** [lark-parser/lark#188]
- Ubuntu 18.04
- Python 3.7.0
- Lark 0.6.1

When I do

```python
>>> from lark import Lark
>>> Lark("/")
```

it raises

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/lark/load_grammar.py", line 579, in load_grammar
    tree = self.canonize_tree.transform( self.parser.parse(grammar_text+'\n') )
  File "/usr/local/lib/python3.7/site-packages/lark/parser_frontends.py", line 36, in parse
    return self.parser.parse(token_stream, *[sps] if sps is not NotImplemented else [])
  File "/usr/local/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 68, in parse
    for i, token in enumerate(stream):
  File "/usr/local/lib/python3.7/site-packages/lark/lexer.py", line 105, in lex
    raise UnexpectedCharacters(stream, line_ctr.char_pos, line_ctr.line, line_ctr.column, state=self.state)
lark.exceptions.UnexpectedCharacters: No terminal defined for '/' at line 1 col 1

/
^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    Lark('/')
  File "/usr/local/lib/python3.7/site-packages/lark/lark.py", line 157, in __init__
    self.grammar = load_grammar(grammar, self.source)
  File "/usr/local/lib/python3.7/site-packages/lark/load_grammar.py", line 581, in load_grammar
    raise GrammarError("Unexpected input %r at line %d column %d in %s" % (e.context, e.line, e.column, name))
AttributeError: 'UnexpectedCharacters' object has no attribute 'context'
```

Please check it.

**Comment by erezsh** [comment]
Thanks, fixed!
