### ISSUE TITLE
AssertionError with an optional rule

### ISSUE THREAD

**Issue by rezemika** [lark-parser/lark#197]
I'm note sure whether it is a bug or not, but since version 0.6.0, the parsing of the following EBNF (extract, [here is the full file](https://github.com/rezemika/oh_sanitizer/blob/e2c3a0b80d7c50bad2a91b9d3f20517119359898/oh_sanitizer/field.ebnf#L105)) raises an AssertionError.

```
MONTH : "Jan"i | "Feb"i | "Mar"i | "Apr"i | "May"i | "Jun"i | "Jul"i | "Aug"i | "Sep"i | "Oct"i | "Nov"i | "Dec"i
year.2 : /([0-9]{4})+/

%import common.INT
PLUS_OR_MINUS : "+" | "-"
day_offset : " " PLUS_OR_MINUS INT (" day" ["s"] | " d")

monthday_date : [year " "] MONTH " " INT -> monthday_date_monthday
              | [year " "] MONTH " " INT "-" INT -> monthday_date_day_to_day
              | [year " "] MONTH -> monthday_date_month
              | [year " "] EASTER -> monthday_date_easter
              | [year " "] EASTER [day_offset] -> monthday_date_easter
```

Here is the traceback.

```
Traceback (most recent call last):
  File "oh_sanitizer/main.py", line 22, in get_parser
    return lark.Lark(grammar, start="time_domain", parser="earley")
  File "/home/rezemika/Programmes/Python/oh_sanitizer/venv/lib/python3.5/site-packages/lark/lark.py", line 160, in __init__
    tokens, self.rules, self.ignore_tokens = self.grammar.compile()
  File "/home/rezemika/Programmes/Python/oh_sanitizer/venv/lib/python3.5/site-packages/lark/load_grammar.py", line 484, in compile
    expansions = rule_tree_to_text.transform(tree)
  File "/home/rezemika/Programmes/Python/oh_sanitizer/venv/lib/python3.5/site-packages/lark/visitors.py", line 53, in transform
    return self._transform_tree(tree)
  File "/home/rezemika/Programmes/Python/oh_sanitizer/venv/lib/python3.5/site-packages/lark/visitors.py", line 49, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "/home/rezemika/Programmes/Python/oh_sanitizer/venv/lib/python3.5/site-packages/lark/visitors.py", line 44, in _transform_children
    yield self._transform_tree(c) if isinstance(c, Tree) else c
  File "/home/rezemika/Programmes/Python/oh_sanitizer/venv/lib/python3.5/site-packages/lark/visitors.py", line 50, in _transform_tree
    return self._call_userfunc(tree, children)
  File "/home/rezemika/Programmes/Python/oh_sanitizer/venv/lib/python3.5/site-packages/lark/visitors.py", line 39, in _call_userfunc
    return f(children)
  File "/home/rezemika/Programmes/Python/oh_sanitizer/venv/lib/python3.5/site-packages/lark/load_grammar.py", line 250, in alias
    assert _alias is None, (alias, expansion, '-', _alias)  # Double alias not allowed
AssertionError: (Token(RULE, 'monthday_date_easter'), ([NonTerminal('year'), Terminal('__IGNORE_0'), Terminal('EASTER'), Terminal('__IGNORE_0')], None), '-', ([NonTerminal('year'), Terminal('__IGNORE_0'), Terminal('EASTER'), Terminal('__IGNORE_0'), NonTerminal('day_offset')], None))
```

This error is solved with the following.

```
monthday_date : [year " "] MONTH " " INT -> monthday_date_monthday
              | [year " "] MONTH " " INT "-" INT -> monthday_date_day_to_day
              | [year " "] MONTH -> monthday_date_month
              | [year " "] EASTER -> monthday_date_easter
              | [year " "] EASTER day_offset -> monthday_date_easter
```

So, I'm note sure it's a bug or a feature, but just in case...

Thank you for this great module! :)

**Comment by erezsh** [comment]
Thanks for the bug report. I pushed a fix to master, please check if it works.

**Comment by rezemika** [comment]
All works fine with the master version. Thank you very much!
