### ISSUE TITLE
AttributeError: 'Derivation' object has no attribute 'rule'

### ISSUE THREAD

**Issue by enawaves** [lark-parser/lark#210]
Im trying to have multiple questions inside a question and for some reason it keeps coming with the same error over and over. The grammar is:

grammar = """
game: GAME string scene_element* -> game

scene_element: "Choice:" choices

choices: "Question" qa

qa: string ":" opt*
  
opt: string "=" string
      | string "=" qa
   
GAME: "GAME"

string: ESCAPED_STRING -> string

%import common.WS
%import common.NUMBER
%import common.ESCAPED_STRING
%ignore WS
"""
parser = Lark(grammar, start='game', ambiguity='explicit')

### The text Im trying to parse is:

GAME "Hello"
    Choice: Question
    "Whats your name?":
        "Jorge" = "Nice name"
        "Ena" = "I love it!"
        "Claudio" = "Like my dog!"
        "I have no name" = "OK":
                                         "Are you sure?" = "Yes"

### And the error is:

Traceback (most recent call last):
  File "/Users/MyUser/Documents/Python/parser/test.py", line 59, in <module>
    print(parser.parse(sentence).pretty())
  File "/Users/MyUser/Documents/Python/parser/venv/lib/python3.6/site-packages/lark/tree.py", line 44, in pretty
    return ''.join(self._pretty(0, indent_str))
  File "/Users/MyUser/Documents/Python/parser/venv/lib/python3.6/site-packages/lark/tree.py", line 37, in _pretty
    l += n._pretty(level+1, indent_str)
  File "/Users/MyUser/Documents/Python/parser/venv/lib/python3.6/site-packages/lark/tree.py", line 37, in _pretty
    l += n._pretty(level+1, indent_str)
  File "/Users/MyUser/Documents/Python/parser/venv/lib/python3.6/site-packages/lark/tree.py", line 37, in _pretty
    l += n._pretty(level+1, indent_str)
  [Previous line repeated 1 more times]
  File "/Users/MyUser/Documents/Python/parser/venv/lib/python3.6/site-packages/lark/tree.py", line 34, in _pretty
    l = [ indent_str*level, self._pretty_label(), '\n' ]
  File "/Users/MyUser/Documents/Python/parser/venv/lib/python3.6/site-packages/lark/parsers/earley.py", line 30, in _pretty_label
    return self.rule.origin if self.rule else self.data
AttributeError: 'Derivation' object has no attribute 'rule'

Thanks!

**Comment by ghamarian** [comment]
I get a similar error, in `concatlabel`, it is left recursive but `++`does not appear anywhere else in the grammar. Here is my grammar.

`?item: identifierlist    -> rv
     | number    
     | "-" item         
     | "(" sum ")"
     | (item ("++" item)+) -> concatlabel
     | distribution "**" int -> tile
     | distribution -> create
`
Wondering if it is an issue or just a bug in my grammar.

**Comment by erezsh** [comment]
Thanks for the bug report! I pushed a fix to the `master` branch.

**Comment by erezsh** [comment]
Also pushed a new version to pypi. Upgrading to `lark-parser==0.6.4` should do the trick.
