### ISSUE TITLE
Lark gives too meaningful names to terminals, but this may not be always wanted

### ISSUE THREAD

**Issue by ForceBru** [lark-parser/lark#224]
Consider the following script to merely display the parse tree for the grammar given later in `G2.txt`:

```
# G2.py
import lark

def non_standalone(code, parser=lark.Lark(open('G2.txt').read(), parser='lalr')):
    return parser.parse(code)

root = non_standalone("(not a parenthesis!(not a parenthesis!))")

print(root.pretty())
```

-----
Here's the first version of `G2.txt`:

```
WHATEVER: "not a parenthesis!"

start: WHATEVER start? | "(" start ")"
```

Here's the output of `python3 G2.py`:
```
start
  start
    not a parenthesis!
    start
      start	not a parenthesis!
```

This works as expected. Now let's go a bit crazy.

-----
Here's the second version of `G2.txt`:

```
LPAR: "not a parenthesis!"

start: LPAR start? | "(" start ")"
```

Yeah, `LPAR` is not a parenthesis at all, but this should be acceptable, to my mind.

Here's the exception raised after running `python3 G2.py`:
```
Traceback (most recent call last):
  File "G2.py", line 9, in <module>
    root = non_standalone(code)
  File "G2.py", line 4, in non_standalone
    return parser.parse(code)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lark_parser-0.6.4-py3.6.egg/lark/lark.py", line 223, in parse
    return self.parser.parse(text)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lark_parser-0.6.4-py3.6.egg/lark/parser_frontends.py", line 38, in parse
    return self.parser.parse(token_stream, *[sps] if sps is not NotImplemented else [])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lark_parser-0.6.4-py3.6.egg/lark/parsers/lalr_parser.py", line 68, in parse
    for i, token in enumerate(stream):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lark_parser-0.6.4-py3.6.egg/lark/lexer.py", line 259, in lex
    for x in l.lex(stream, self.root_lexer.newline_types, self.root_lexer.ignore_types):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lark_parser-0.6.4-py3.6.egg/lark/lexer.py", line 105, in lex
    raise UnexpectedCharacters(stream, line_ctr.char_pos, line_ctr.line, line_ctr.column, state=self.state)
lark.exceptions.UnexpectedCharacters: No terminal defined for '(' at line 1 col 1

(not a parenthesis!(not a parenthesis!))
^
```

While using Lark, I noticed that it names anonymous (_anonymous_!) terminals (like `"("` and `")"`) in `"(" start ")"` _and_ the names are very meaningful (`LPAR` and `RPAR` in this case; there are probably many more). Apparently, when you use these names explicitly in your grammar, the two tokens (auto-generated by Lark and created by user) somehow collide, which messes up the parse.

**Comment by erezsh** [comment]
Thanks for the bug report! I pushed a fix to `master`, it should behave correctly now.
