### ISSUE TITLE
Regular Expressions - Match Anything

### ISSUE THREAD

**Issue by solartes** [lark-parser/lark#257]
I wanna a regular expression which match anything like numbers, Spanish words, format numbers e.g: ¡Hola! Mi nombre es Julian y tengo 22 años mi identificación es 1.22-46646

I have tried: .* but it does not work

**Comment by SupraSummus** [comment]
for me it works: `lark.Lark('start: /.+/').parse('ąðć')`

`\.*\` is apparently not permitted for earley parser because it matches zero-length string.

Also you probably need to exclude terminating character from the matched string, to make it possible to terminate. For example if you want to use space you'll write `start: /[^ ]+/`.

**Comment by brando90** [comment]
this didn't work for me. Error:
```
from lark import Lark
parser: Lark = Lark(r"""
    rterm: "(___hole 0" anything  ")" | ESCAPED_STRING
    
    anything: /.+/
    
    %import common.ESCAPED_STRING 
    %import common.SIGNED_NUMBER
    %import common.WS
    %ignore WS
    """, start='rterm')
test_strings: list[str] = ["(___hole 0 (fun n : nat => ___hole 1 (___hole 2 eq_refl : 0 + n = n)))"]
for test in test_strings:
    print(test)
    print(parser.parse(test).pretty())
(___hole 0 (fun n : nat => ___hole 1 (___hole 2 eq_refl : 0 + n = n)))
Traceback (most recent call last):
  File "/Users/brandomiranda/miniconda/envs/iit_term_synthesis/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-5499195ecb8d>", line 18, in <cell line: 16>
    print(parser.parse(test).pretty())
  File "/Users/brandomiranda/miniconda/envs/iit_term_synthesis/lib/python3.9/site-packages/lark/lark.py", line 581, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/Users/brandomiranda/miniconda/envs/iit_term_synthesis/lib/python3.9/site-packages/lark/parser_frontends.py", line 106, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "/Users/brandomiranda/miniconda/envs/iit_term_synthesis/lib/python3.9/site-packages/lark/parsers/earley.py", line 305, in parse
    raise UnexpectedEOF(expected_terminals, state=frozenset(i.s for i in to_scan))
lark.exceptions.UnexpectedEOF: Unexpected end-of-input. Expected one of: 
	* RPAR
```

**Comment by brando90** [comment]
@SupraSummus what is the meaning of the forward slashes in `/.*/`?

**Comment by asarkar** [comment]
@brando90 It is the syntax for regex, see https://lark-parser.readthedocs.io/en/latest/grammar.html#terminals.
