### ISSUE TITLE
New propagate_positions issues in v0.6.5

### ISSUE THREAD

**Issue by mlin** [lark-parser/lark#275]
Great work on lark!

I use transformers with `v_args(meta=True)` and on upgrading from 0.6.4 to v0.6.5 I noticed that a few of my productions now get passed an empty `meta` object, that is the assertion `assert hasattr(meta,'line') or meta.empty is True` passes. It seems to be only a couple out of a few dozen productions so affected.

I'm trying to narrow it down further and will update here.

Our parser FWIW: https://github.com/chanzuckerberg/miniwdl/blob/master/WDL/_parser.py
The `document` and `placeholder` productions seem to be affected but others receive the position information as expected.

**Comment by erezsh** [comment]
Do the affected productions contain any terminals? And if not, does one of their descendants contain any terminals?

**Comment by mlin** [comment]
Here's a reproduction I hacked out:

https://gist.github.com/mlin/a7a1bb4fd8523adcc41bfa68521b61cf

It parses two strings in the language, the first one behaves as expected, and in the second one `meta` is empty for the `document` transformer. 

```
$ python3 /tmp/lark275.py 
quick/brown/fox
Traceback (most recent call last):
  File "/tmp/lark275.py", line 39, in <module>
    """))
  File "/tmp/lark275.py", line 30, in p
    return MyTransformer().transform(lark.Lark(grammar, start="document", parser="lalr", propagate_positions=True).parse(txt))
  File "/home/mlin/.local/lib/python3.6/site-packages/lark/visitors.py", line 54, in transform
    return self._transform_tree(tree)
  File "/home/mlin/.local/lib/python3.6/site-packages/lark/visitors.py", line 51, in _transform_tree
    return self._call_userfunc(tree, children)
  File "/home/mlin/.local/lib/python3.6/site-packages/lark/visitors.py", line 32, in _call_userfunc
    return f(children, tree.meta)
  File "/home/mlin/.local/lib/python3.6/site-packages/lark/visitors.py", line 235, in f
    return _f(self, *args, **kwargs)
  File "/tmp/lark275.py", line 26, in document
    assert hasattr(meta, 'line')
AssertionError
```

Thanks so much for taking a look @erezsh !

**Comment by erezsh** [comment]
Thanks for the bug report @mlin 

This bug seems to be solved in branch "0.7", which is stable. Please use it (if necessary) until I make the 0.7 release official.
