### ISSUE TITLE
v0.6.6 false "Rules defined twice" error (on questionable grammar)

### ISSUE THREAD

**Issue by mlin** [lark-parser/lark#315]
In lark v0.6.6 (presumably 00510edee6e8887c249e0d2f2ac390eead0a538d), [this short example](https://gist.github.com/mlin/5314b9e2f736e263c698848de5651811) fails with:

```
$ python3 lark315.py
Traceback (most recent call last):
  File "/tmp/larkbug.py", line 15, in <module>
    """))
  File "/tmp/larkbug.py", line 11, in p
    return lark.Lark(grammar, start="string", parser="lalr", propagate_positions=True).parse(txt)
  File "/home/mlin/.local/lib/python3.6/site-packages/lark/lark.py", line 169, in __init__
    self.parser = self._build_parser()
  File "/home/mlin/.local/lib/python3.6/site-packages/lark/lark.py", line 193, in _build_parser
    return self.parser_class(self.lexer_conf, parser_conf, options=self.options)
  File "/home/mlin/.local/lib/python3.6/site-packages/lark/parser_frontends.py", line 49, in __init__
    self.parser = lalr_parser.Parser(parser_conf, debug=debug)
  File "/home/mlin/.local/lib/python3.6/site-packages/lark/parsers/lalr_parser.py", line 14, in __init__
    analysis = LALR_Analyzer(parser_conf, debug=debug)
  File "/home/mlin/.local/lib/python3.6/site-packages/lark/parsers/grammar_analysis.py", line 117, in __init__
    raise GrammarError("Rules defined twice: %s" % ', '.join(str(i) for i in duplicates))
lark.exceptions.GrammarError: Rules defined twice: <string : >
```

It has something to do with the `[CNAME*]` construct where the square brackets are redundant (admittedly, this is a corner case arising from an oversight in our grammar). If you remove the square brackets, or change the * to a +, it works.

**Comment by erezsh** [comment]
Fixed
