### ISSUE TITLE
'Endswith' syntax in lark

### ISSUE THREAD

**Issue by Xilpex** [lark-parser/lark#354]
Is there an 'endswith' type of keyword in lark? Is there a way to make sure lines end with a character (suppose a semi colon)?

**Comment by erezsh** [comment]
Sure.. How about

```ruby
line: line_contents ";" _NL
_NL: /\n+/
```

**Comment by Xilpex** [comment]
@erezsh -- I am getting this error when I use your code:

```python
GrammarError: Unexpected input at line 20 column 10 in <string>: 

    _NL: /
         ^
```

And here is my lark code:

```python
    ?start: sum
          | NAME "=" sum       -> assign_var
    ?sum: product
        | sum "+" product      -> add
        | sum "-" product      -> subtract
    ?product: atom
        | product "*" atom     -> multiply
        | product "/" atom     -> divide
    ?atom: NUMBER              -> number
         | "-" atom            -> neg
         | NAME                -> var
         | "(" sum ")"

    %import common.CNAME -> NAME
    %import common.NUMBER
    %import common.WS_INLINE
    %ignore WS_INLINE
    line: line_contents ";" _NL
    _NL: /\n+/
```

No matter where I place the statement you gave me, I get the error. (Sorry, its my first day using lark :D)

**Comment by erezsh** [comment]
Strange error. Can you post the entire code? Ideally on pastebin.org or similar

**Comment by erezsh** [comment]
Btw, make sure you're using a raw string `r""" something something """`

**Comment by Xilpex** [comment]
The full code is [here][1]. All it is, is an adapted version of the `calc.py` example. Here is the full error:

```python
Traceback (most recent call last):
  File "C:\Python27\parser_test.py", line 49, in <module>
    calc_parser = Lark(calc_grammar, parser='lalr', transformer=CalculateTree())
  File "C:\Python27\lib\site-packages\lark\lark.py", line 170, in __init__
    self.grammar = load_grammar(grammar, self.source)
  File "C:\Python27\lib\site-packages\lark\load_grammar.py", line 691, in load_grammar
    (e.line, e.column, grammar_name, context))
GrammarError: Unexpected input at line 20 column 10 in <string>: 

    _NL: /
         ^
```

  [1]: https://pastebin.com/ABAuSiwP

**Comment by erezsh** [comment]
> make sure you're using a raw string

**Comment by Xilpex** [comment]
Even when I use a raw string, I get the same error.

**Comment by erezsh** [comment]
```python
calc_grammar = r"""
        ?start: sum
          | NAME "=" sum       -> assign_var
    ?sum: product
        | sum "+" product      -> add
        | sum "-" product      -> subtract
    ?product: atom
        | product "*" atom     -> multiply
        | product "/" atom     -> divide
    ?atom: NUMBER              -> number
         | "-" atom            -> neg
         | NAME                -> var
         | "(" sum ")"

    %import common.CNAME -> NAME
    %import common.NUMBER
    %import common.WS_INLINE
    %ignore WS_INLINE
    line: "A" ";" _NL
    _NL: /\n+/
"""
```
Works just fine
