### ISSUE TITLE
Adding components to calc.py

### ISSUE THREAD

**Issue by Xilpex** [lark-parser/lark#355]
I looked at `calc.py` in the examples, and wanted to add more math operators. To do so, I edited `calc.py` to look like this:

```python
from lark import Lark, Transformer, v_args

calc_grammar = """
    ?start: sum
          | NAME "=" sum ";"   -> assign_var
    ?sum: product
        | sum "+" product      -> add
        | sum "-" product      -> subtract
    ?product: misc
        | product "*" atom     -> multiply
        | product "/" atom     -> divide
    ?misc: atom
        | exponent "**" atom   -> exponent
        | modulus "%" atom     -> modulus
    ?atom: NUMBER              -> number
         | "-" atom            -> neg
         | NAME                -> var
         | "(" (sum misc) ")" 
    %import common.CNAME -> NAME
    %import common.NUMBER
    %import common.WS_INLINE
    %ignore WS_INLINE
"""


@v_args(inline=True)    # Affects the signatures of the methods
class CalculateTree(Transformer):
    from operator import neg
    from my_ast.math_ast import add, subtract, multiply, divide, exponent, modulus
    number = float

    def __init__(self):
        self.vars = {}

    def assign_var(self, name, value):
        self.vars[name] = value
        return value

    def var(self, name):
        return self.vars[name]


calc_parser = Lark(calc_grammar, parser='lalr', transformer=CalculateTree())
calc = calc_parser.parse


def main():
    while True:
        try:
            repl_in = raw_input('> ')
        except EOFError:
            break
        print(calc(repl_in)) 


if __name__ == '__main__':
    main()
```
The lark and python code above looks fine to me, but when I ran the code I got this error:

```python
Traceback (most recent call last):
  File "C:/Users/Xilpex/Desktop/Qxc/Qxc.py", line 44, in <module>
    calc_parser = Lark(calc_grammar, parser='lalr', transformer=CalculateTree())
  File "C:\Python27\lib\site-packages\lark\lark.py", line 170, in __init__
    self.grammar = load_grammar(grammar, self.source)
  File "C:\Python27\lib\site-packages\lark\load_grammar.py", line 832, in load_grammar
    raise GrammarError("Rule '%s' used but not defined (in rule %s)" % (sym, name))
GrammarError: Rule 'modulus' used but not defined (in rule misc)
```

Why am I getting this error? Is there some way I can change my lark or python code to fix this?

**Comment by erezsh** [comment]
You can't do recursion with aliases. You have define a separate rule.

**Comment by Xilpex** [comment]
@erezsh The problem is, if I define a separate rule, I won't be able to set a variable to it...

**Comment by erezsh** [comment]
What's wrong with this?

```ruby
    ?misc: atom
        | exponent "**" atom   -> exponent
        | modulus

modulus: (modulus "%")? atom
```

**Comment by Xilpex** [comment]
@erezsh -- I've change my lark code to this:

```bash
    ?start: sum
          | NAME "=" sum ";"   -> assign_var
          
    ?sum: product
        | sum "+" product      -> add
        | sum "-" product      -> sub
        
    ?product: misc
        | product "*" atom     -> mul
        | product "/" atom     -> divide
        
    ?misc: atom
        | exponent             -> pow
        | modulus              -> mod
        
    modulus: (modulus "%")? atom
    exponent: (exponent "**")? atom
    
    ?atom: NUMBER              -> number
         | "-" atom            -> neg
         | NAME                -> var
         | "(" (sum misc) ")"
         
    %import common.CNAME -> NAME
    %import common.NUMBER
    %import common.WS_INLINE
    %ignore WS_INLINE
```

But I am getting this error:

```python
Traceback (most recent call last):
  File "C:\Python27\parser_test.py", line 50, in <module>
    calc_parser = Lark(calc_grammar, parser='lalr', transformer=CalculateTree())
  File "C:\Python27\lib\site-packages\lark\lark.py", line 191, in __init__
    self.parser = self._build_parser()
  File "C:\Python27\lib\site-packages\lark\lark.py", line 215, in _build_parser
    return self.parser_class(self.lexer_conf, parser_conf, options=self.options)
  File "C:\Python27\lib\site-packages\lark\parser_frontends.py", line 48, in __init__
    self.parser = lalr_parser.Parser(parser_conf, debug=debug)
  File "C:\Python27\lib\site-packages\lark\parsers\lalr_parser.py", line 15, in __init__
    analysis.compute_lookahead()
  File "C:\Python27\lib\site-packages\lark\parsers\lalr_analysis.py", line 100, in compute_lookahead
    for _ in bfs([self.start_state], step):
  File "C:\Python27\lib\site-packages\lark\utils.py", line 40, in bfs
    for next_node in expand(node):
  File "C:\Python27\lib\site-packages\lark\parsers\lalr_analysis.py", line 96, in step
    raise GrammarError("Collision in %s: %s" %(k, ', '.join(['\n  * %s: %s' % x for x in v])))
GrammarError: Collision in Terminal('LPAR'): 
  * Reduce: <exponent : atom>, 
  * Reduce: <modulus : atom>, 
  * Reduce: <misc : atom>
```

Is there some way I can change my lark code to fix this error? My python code is `calc.py`, except more objects are imported from the operator module; Here is everything imported from the operator module:

```python
from operator import neg, add, sub, mul, truediv as divide, pow, mod
```

**Comment by erezsh** [comment]
You have to specify the priority by creating a "flow" of rules. See how calc is written: `sum` into `product` into `atom`. You have to keep the flow going, instead of having multiple rules pointing to the same resolution.

Read up on LALR. Or just use Earley, which will work no matter how you write your grammar.

**Comment by Xilpex** [comment]
@erezsh -- So, I have to make it `sum` into `product` into `misc` into atom? Will that work?

**Comment by Xilpex** [comment]
Oh, could you give me a link to a good lalr article? I'm finding it kind of hard to find one. =) Thanks.

**Comment by erezsh** [comment]
See this: http://blog.erezsh.com/how-to-write-a-calculator-in-50-python-lines-without-eval/

It's a tutorial for my old library, but it gives a good idea of the right technique for LALR

**Comment by Xilpex** [comment]
@erezsh Thanks! =D
