### ISSUE TITLE
Can't get multi-line code to work

### ISSUE THREAD

**Issue by GarbageCollections** [lark-parser/lark#368]
Grammar(excerpted):
```
_NL: (/\r?\n/)+
WS: (" " | /\t/)+
%ignore WS

TYPES: "u8" | "u16" | "u32" | "u64"
    | "i8" | "i16" | "i32" | "i64"
    | "bool"
TYPES_W_LET: TYPES | "let"

%import common.INT -> INTEGER
DEC_INTEGER: INTEGER

//start=statement
statement: declaration _NL
          | _NL

declaration: TYPES_W_LET IDENTIFIER "=" value

?value: DEC_INTEGER
     | "(" value ")"
```

Test code:
```

let i = 0
let p = 123
```

Tokens:
```
let
i
=
0


let
b
=
123
```

Error message:
```
lark.exceptions.UnexpectedCharacters: No terminal defined for 'l' at line 2 col 1
let i = 0
^
```

The grammar above can only deal with single line of code.
What should I do to get multi-line code work too?

**Comment by GarbageCollections** [comment]
Python code:
```python
GRAMMAR = """
_NL: (/\r?\n/)+
WS: (" " | /\t/)+
%ignore WS

TYPES: "u8" | "u16" | "u32" | "u64"
    | "i8" | "i16" | "i32" | "i64"
    | "bool"
TYPES_W_LET: TYPES | "let"

%import common.INT -> INTEGER
DEC_INTEGER: INTEGER

//start=statement
statement: declaration _NL
          | _NL

declaration: TYPES_W_LET IDENTIFIER "=" value

?value: DEC_INTEGER
     | "(" value ")"
"""
parser = Lark(grammar=GRAMMAR, start='statement')

    test_code = """
    let i = 0
    let p = 123
"""
toks = parser.lex(test_code)
for tok in toks:
    print(tok)
print(parser.parse(test_code).pretty())
```

**Comment by erezsh** [comment]
Post code that actually works. What you wrote here throws:
```python
Traceback (most recent call last):
  File "issue368.py", line 24, in <module>
    parser = Lark(grammar=GRAMMAR, start='statement')
  File "/home/erez/lark/lark/lark.py", line 200, in __init__
    self.grammar = load_grammar(grammar, self.source)
  File "/home/erez/lark/lark/load_grammar.py", line 838, in load_grammar
    raise GrammarError("Token '%s' used but not defined (in rule %s)" % (sym, name))
lark.exceptions.GrammarError: Token 'IDENTIFIER' used but not defined (in rule declaration)
```

Also, you're trying to parse several statements, but you only defined a single one.. (without loop or recursion)

**Comment by GarbageCollections** [comment]
That mean I should have `*` after `declaration` like this?
```
statement: declaration* _NL
          | _NL
```

**Comment by erezsh** [comment]
Probably more like:

```python
statement: (declaration? _NL)+
```

**Comment by GarbageCollections** [comment]
Thank you for solving my problem! It's really helped me.
But after fixing this it comes with a new problem, it throws me this:
```
lark.exceptions.ParseError: Unexpected end of input! Expecting a terminal of:
blah..blah..blah...
```
It happen when I parse text with file input, it might contain EOF (I think?)

this is my code:

```python
from lark import Lark

if __name__ == '__main__':
    with open('grammar.lark', 'r') as f:
            GRAMMAR = f.read()
    parser = Lark(grammar=GRAMMAR, start='start', propagate_positions=True)

    test_code = open('testcode.flo', 'r', encoding='utf-8').read()
    
    toks = parser.lex(test_code)
    for tok in toks:
        print(tok)
    print(parser.parse(test_code).pretty())
```
grammar.lark:
```
_NL: (/\r?\n/)+
WS: (" " | /\t/)+
%ignore WS

%import common.CNAME -> IDENTIFIER

TYPES: "u8" | "u16" | "u32" | "u64"
    | "i8" | "i16" | "i32" | "i64"
    | "bool"
TYPES_W_LET: TYPES | "let"

%import common.INT -> INTEGER
DEC_INTEGER: INTEGER

//start=start
start: (statement? _NL)+
?statement: declaration
        // there are few more in my actual project

declaration: TYPES_W_LET IDENTIFIER "=" value

?value: DEC_INTEGER
     | "(" value ")"
```
How to get this work?

**Comment by erezsh** [comment]
The easiest trick is to just add `'\n'` to every input you're going to parse.

**Comment by GarbageCollections** [comment]
Thank you! This helped me a lot!
