### ISSUE TITLE
Custom lexers documented but not implemented

### ISSUE THREAD

**Issue by garcia** [lark-parser/lark#377]
Custom lexers with LALR are documented in the examples here: https://github.com/lark-parser/lark/blob/master/examples/custom_lexer.py

However, this example raises an exception upon parsing:
```
PS D:\GitHub\project> python .\custom_lexer.py
['alice', 1, 27, 3, 'bob', 4, 'carrie', 'dan', 8, 6]
Traceback (most recent call last):
  File ".\custom_lexer.py", line 55, in <module>
    test()
  File ".\custom_lexer.py", line 47, in test
    tree = parser.parse(data)
  File "C:\Python36\lib\site-packages\lark\lark.py", line 292, in parse
    return self.parser.parse(text)
  File "C:\Python36\lib\site-packages\lark\parser_frontends.py", line 77, in parse
    token_stream = self.lex(text)
  File "C:\Python36\lib\site-packages\lark\parser_frontends.py", line 73, in lex
    stream = self.lexer.lex(text)
AttributeError: 'NoneType' object has no attribute 'lex'
```

It looks the feature is not actually implemented, judging by the stubbed `__init__` method in `LALR_CustomLexer`: https://github.com/lark-parser/lark/blob/master/lark/parser_frontends.py#L109

This would be a very useful feature, as I don't need lexing for my use case and would rather provide a direct token stream.

**Comment by erezsh** [comment]
You're right, there has been a regression. I pushed a fix for it to `master`.
