### ISSUE TITLE
lark grammar allows question marker after Operators * and +

### ISSUE THREAD

**Issue by MegaIng** [lark-parser/lark#511]
https://github.com/lark-parser/lark/blob/2f92c7b4a79298eb0e11fd87b2550ac1c7f3e73e/examples/lark.lark#L36

While this is not really a problem, I am wondering why it is implemented at all. This is the same in the actual parser inside `load_grammar`, which throws this kind of construct out at a later point with a confusing error message (VistorError caused by AssertionError) without any context:
```

Traceback (most recent call last):
  File "C:\Users\tramp\PycharmProjects\lark-linter\venv\lib\site-packages\lark\visitors.py", line 41, in _call_userfunc
    return f(*children)
  File "C:\Users\tramp\PycharmProjects\lark-linter\venv\lib\site-packages\lark\visitors.py", line 277, in f
    return _f(self, *args, **kwargs)
  File "C:\Users\tramp\PycharmProjects\lark-linter\venv\lib\site-packages\lark\load_grammar.py", line 202, in expr
    assert False, op
AssertionError: +?
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\tramp\PycharmProjects\lark-linter\venv\lib\site-packages\lark\lark.py", line 207, in __init__
    self.terminals, self.rules, self.ignore_tokens = self.grammar.compile(self.options.start)
  File "C:\Users\tramp\PycharmProjects\lark-linter\venv\lib\site-packages\lark\load_grammar.py", line 507, in compile
    res = ebnf_to_bnf.transform(tree)
  File "C:\Users\tramp\PycharmProjects\lark-linter\venv\lib\site-packages\lark\visitors.py", line 152, in transform
    subtree.children = list(self._transform_children(subtree.children))
  File "C:\Users\tramp\PycharmProjects\lark-linter\venv\lib\site-packages\lark\visitors.py", line 71, in _transform_children
    yield self._transform_tree(c)
  File "C:\Users\tramp\PycharmProjects\lark-linter\venv\lib\site-packages\lark\visitors.py", line 148, in _transform_tree
    return self._call_userfunc(tree)
  File "C:\Users\tramp\PycharmProjects\lark-linter\venv\lib\site-packages\lark\visitors.py", line 51, in _call_userfunc
    raise VisitError(tree, e)
lark.exceptions.VisitError: Error trying to process rule "expr":
+?
```

**Comment by erezsh** [comment]
Good catch. `*?` doesn't make sense, and `+?` is just a longer version of `*`. So I agree that neither should be allowed.

**Comment by erezsh** [comment]
Syntax removed. Thanks for opening the issue!

I don't even remember why it's there. My guess is that this is a relic that I copied from plyplus, where `+?` and `*` created slightly different rule structures for PLY.
