### ISSUE TITLE
Standalone parser crashes with 'visitors not defined'

### ISSUE THREAD

**Issue by ReedOei** [lark-parser/lark#514]
It seems the new release has broken something in the standalone parser generator.

Steps to reproduce:

Sample grammar:
```
?start: INT -> int_const

%import common.INT
```

Run this command:
```
python3 -m lark.tools.standalone "fail_grammar.lark" "start" > "test_parser.py"
```

And run the following Python file:
```
from lark import Lark, Transformer, v_args

@v_args(inline=True)
class ExampleTransformer(Transformer):
    def int_const(self, val):
        return int(val)

from test_parser import Lark_StandAlone

t = Lark_StandAlone(transformer=ExampleTransformer())
```

This gives:
```
roei@roei-main:~/Pecan$ python3 fail_parser.py 
Traceback (most recent call last):
  File "fail_parser.py", line 10, in <module>
    t = Lark_StandAlone(transformer=ExampleTransformer())
  File "/home/roei/Pecan/test_parser.py", line 2059, in Lark_StandAlone
    return Lark.deserialize(DATA, namespace, MEMO, transformer=transformer, postlex=postlex)
  File "/home/roei/Pecan/test_parser.py", line 1999, in deserialize
    inst._prepare_callbacks()
  File "/home/roei/Pecan/test_parser.py", line 1981, in _prepare_callbacks
    self._callbacks = self._parse_tree_builder.create_callback(self.options.transformer)
  File "/home/roei/Pecan/test_parser.py", line 1480, in create_callback
    f = apply_visit_wrapper(f, user_callback_name, wrapper)
  File "/home/roei/Pecan/test_parser.py", line 1435, in apply_visit_wrapper
    if wrapper is visitors._vargs_meta or wrapper is visitors._vargs_meta_inline:
NameError: name 'visitors' is not defined
```

**Comment by erezsh** [comment]
Thanks for letting me know, and sorry for the oversight.

I just pushed a commit that should solve it.

I'll send a new release to pypi soon.

**Comment by ReedOei** [comment]
No worries, thanks for the quick response.
