### ISSUE TITLE
How to fix problem with collision

### ISSUE THREAD

**Issue by zurgeg** [lark-parser/lark#547]
```
psl_grammer = '''
?start: value
?value: WORD
      | ifexpr
      | expr
      | stmt
      | numstmt
      | varstmt
ifexpr: "if" value ":"
stmt: "=>"
numstmt: expr stmt expr
expr: add
    | subtract
    | divide
    | multiply
    | NUMBER
add:  expr "+" expr
subtract: expr "-" expr 
divide: expr "/" expr
multiply: expr "*" expr
gvarstmt: WORD ">>" 
varstmt: WORD "=" value

%import common.NUMBER
%import common.WORD
%ignore " "
'''

p = Lark(psl_grammer, parser='lalr')

prsd = p.parse('1+2+1+1-2*2/2')
print(prsd)

prsd2 = p.parse('if 1 => 2+2:')

prsd3 = p.parse('hello=if 2+2 => 4+4:')

prsd4 = p.parse('hello >>')
NAMESPACE = {}
class PSTransformer(Transformer):
    def __init__(self):
        self.tsum = 0
        self.glob = {}
    def expr(self, numbers):
        
        addo = []
        subo = []
        mulo = []
        divo = []
        
        try:
            print(numbers)
            rt = float(numbers[0])
            print(rt)
            #return rt
        except:
            
            if numbers[0].data == 'add':
                self.tsum = numbers[0].children[1] + numbers[0].children[0] #Embrace the communitve property!
            elif numbers[0].data == 'subtract':
                self.tsum = numbers[0].children[0] - numbers[0].children[1]
            elif numbers[0].data == 'multiply':
                self.tsum = numbers[0].children[1] * numbers[0].children[0] #Embrace the communitve property!
            if numbers[0].data == 'divide':
                self.tsum = numbers[0].children[0] / numbers[0].children[1] #Embrace the communitve property!
            rt = self.tsum
        return rt
    def ifexpr(self,exp):
        print(exp)
        if exp[0].data == 'numstmt':
            for i in exp[0].children:
                if type(i) == type(1.0):
                    try:
                        self.glob['NUMSTMT_TESTCONDS'].append(i)
                    except KeyError:
                        self.glob['NUMSTMT_TESTCONDS'] = [i]


                else:
                    pass
            if self.glob['NUMSTMT_TESTCONDS'][0] == self.glob['NUMSTMT_TESTCONDS'][1]:
                return True
            else:
                return False
                
        else:
            print('Well, that\'s stinky! That\'s not something that\'s supported!')
            return True
    def varstmt(self,vstmt):
        global NAMESPACE
        print('Hi!')
        print(vstmt)
        NAMESPACE[str(vstmt[0])] = vstmt[1]
    def gvarstmt(self,vstmt):
        print(vstmt)
print(PSTransformer().transform(prsd))
print(PSTransformer().transform(prsd2))
print(PSTransformer().transform(prsd3))
```
For some reason ```prsd3``` fails with:
````
Traceback (most recent call last):
  File "C:\Users\USER\OneDrive\Documents\PoopityScoopLang\parser.py", line 65, in <module>
    prsd4 = p.parse('hello >')
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\lark\lark.py", line 333, in parse
    return self.parser.parse(text, start=start)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\lark\parser_frontends.py", line 125, in parse
    return self._parse(token_stream, start, set_parser_state)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\lark\parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\lark\parsers\lalr_parser.py", line 35, in parse
    return self.parser.parse(*args)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\lark\parsers\lalr_parser.py", line 83, in parse
    for token in stream:
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\lark\lexer.py", line 376, in lex
    for x in l.lex(stream, self.root_lexer.newline_types, self.root_lexer.ignore_types):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37-32\lib\site-packages\lark\lexer.py", line 182, in lex
    raise UnexpectedCharacters(stream, line_ctr.char_pos, line_ctr.line, line_ctr.column, allowed=allowed, state=self.state, token_history=last_token and [last_token])
lark.exceptions.UnexpectedCharacters: No terminal defined for '>' at line 1 col 7

hello >
      ^

Expecting: {'COLON', 'EQUAL'}

Previous tokens: Token(WORD, 'hello')
```
Can anyone help? 
Thanks in advance.

**Comment by erezsh** [comment]
Literally, "No terminal defined for '>' "

Your grammar only defines ">>" and "=>"

**Comment by zurgeg** [comment]
I know, I noticed this and typed in hello >> but it still says "No terminal
defined for >"

**Comment by zurgeg** [comment]
As per my last comment, I am going to reopen.

**Comment by erezsh** [comment]
You can still comment. But if you want to be answered seriously, you need to be serious about your question, and make sure you tried everything obvious first.

**Comment by zurgeg** [comment]
My only guess was to change >> to > in the terminal definitions, and change
hello >> to hello >, which didn’t work (still gave “No terminal defined”)
error.
