### ISSUE TITLE
Unexpected Token LALR contexutual lexer

### ISSUE THREAD

**Issue by belerico** [lark-parser/lark#552]
Hi, i'm trying to parse an asciimath input following a grammar similar to that defined [here](http://asciimath.org/#syntax) and i'm having trouble to understand why with the following code
 ```python
from lark import Lark

grammar = r"""
    %import common.WS
    %import common.LETTER
    %import common.NUMBER
    %ignore WS
    start: i+ -> exp
    _csl: start ("," start)* ","?                   // csl = Comma Separated List
    i: s -> exp_interm
    s: _l _csl? _r -> exp_par
        | _c -> symbol
    _c: LETTER
        | NUMBER
        | P
    P: "|" | "'" | "." | "," // punctuation
    !_l: "(" | "[" | "{" // left parenthesis
    !_r: ")" | "]" | "}" // right parenthesis
"""
parser = Lark(grammar, parser="lalr")
text = ",[1,2]"
print(parser.parse(text).pretty())
```
in which the grammar is a subset of the complete one, the text `,[1,2]` gets correctly parsed as
```
exp
  exp_interm
    symbol      ,
  exp_interm
    exp_par
      [
      exp
        exp_interm
          symbol        1
      exp
        exp_interm
          symbol        2
      ]
```
while `[1,2],` receive the following error
```python
Traceback (most recent call last):
  File "/home/belerico/miniconda3/envs/sciq/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 61, in get_action
    return states[state][token.type]
KeyError: 'COMMA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/belerico/Desktop/projects/sciq/lark_error.py", line 22, in <module>
    print(parser.parse(text).pretty())
  File "/home/belerico/miniconda3/envs/sciq/lib/python3.8/site-packages/lark/lark.py", line 366, in parse
    return self.parser.parse(text, start=start)
  File "/home/belerico/miniconda3/envs/sciq/lib/python3.8/site-packages/lark/parser_frontends.py", line 125, in parse
    return self._parse(token_stream, start, set_parser_state)
  File "/home/belerico/miniconda3/envs/sciq/lib/python3.8/site-packages/lark/parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "/home/belerico/miniconda3/envs/sciq/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 35, in parse
    return self.parser.parse(*args)
  File "/home/belerico/miniconda3/envs/sciq/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 85, in parse
    action, arg = get_action(token)
  File "/home/belerico/miniconda3/envs/sciq/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 64, in get_action
    raise UnexpectedToken(token, expected, state=state)
lark.exceptions.UnexpectedToken: Unexpected token Token(COMMA, ',') at line 1, column 2.
Expected one of: 
        *
```
but i'm expecting a result like this one
```
exp
  exp_interm
    exp_par
      [
      exp
        exp_interm
          symbol        1
      exp
        exp_interm
          symbol        2
      ]
  exp_interm
    symbol      ,
```
Sorry if it's only a dumb mistake, but i'm really new in this parsing and grammar field and thank you in advance!
Yeah

**Comment by erezsh** [comment]
You're mixing "," in two different terminals(`P` and `","`), which might cause the parser to match the "wrong" one.

It might be something else, but in general it's best for a symbol to be defined by one terminal only, or to be easily distinguishable by its surroundings.

**Comment by belerico** [comment]
Sorry for the late response: I've change the grammar so that is not ambiguous. Thank you!

**Comment by erezsh** [comment]
Happy to help
