### ISSUE TITLE
AttributeError with earley when ambiguity=explicit

### ISSUE THREAD

**Issue by jnwatson** [lark-parser/lark#601]
**Describe the bug**

For a particular grammar and a string that is ambiguous, the parse method when `ambiguity=explicit` raises an Attribute Error. I expect it to return a tree with _ambig nodes in it.

The following code:

```import lark

grammar = r'''
query: _querystart
_querystart: stormcmd [ _WSCOMM "|" _WSCOMM _querystart ]
stormcmd: /[a-z]+/ [_WS stormcmdargs]
stormcmdargs: _WS? _cmdargv (_WS _cmdargv)*
_cmdargv: /[\w\/][^ \n\=\|\)]*/
_WSCOMM: (/\/\/[^\n]*/ | _WS)+
_WS: " " | "\n"
'''

def bug_func():
    query = 'tee tee //faz\n | tee'
    parser = lark.Lark(grammar, start='query', debug=True, ambiguity='explicit')
    parser.parse(query)

bug_func()
```

emits the following exception trace:
```
Traceback (most recent call last):
  File "/home/nic/tmp/lark_bug.py", line 18, in <module>
    bug_func()
  File "/home/nic/tmp/lark_bug.py", line 16, in bug_func
    parser.parse(query)
  File "/home/nic/.pyenv/versions/3.7.1/lib/python3.7/site-packages/lark/lark.py", line 368, in parse
    return self.parser.parse(text, start=start)
  File "/home/nic/.pyenv/versions/3.7.1/lib/python3.7/site-packages/lark/parser_frontends.py", line 194, in parse
    return self._parse(text, start)
  File "/home/nic/.pyenv/versions/3.7.1/lib/python3.7/site-packages/lark/parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "/home/nic/.pyenv/versions/3.7.1/lib/python3.7/site-packages/lark/parsers/earley.py", line 319, in parse
    return forest_tree_visitor.visit(solutions[0])
  File "/home/nic/.pyenv/versions/3.7.1/lib/python3.7/site-packages/lark/parsers/earley_forest.py", line 281, in visit
    return super(ForestToTreeVisitor, self).visit(root)
  File "/home/nic/.pyenv/versions/3.7.1/lib/python3.7/site-packages/lark/parsers/earley_forest.py", line 210, in visit
    if isinstance(current, PackedNode):    vpno(current)
  File "/home/nic/.pyenv/versions/3.7.1/lib/python3.7/site-packages/lark/parsers/earley_forest.py", line 352, in visit_packed_node_out
    result = self.callbacks[node.rule](self.output_stack.pop().children)
  File "/home/nic/.pyenv/versions/3.7.1/lib/python3.7/site-packages/lark/parse_tree_builder.py", line 187, in __call__
    return self.node_builder(children)
  File "/home/nic/.pyenv/versions/3.7.1/lib/python3.7/site-packages/lark/parse_tree_builder.py", line 81, in __call__
    filtered += children[i].children
AttributeError: 'Token' object has no attribute 'children'
```

The grammar might not make a whole lot of sense because it is a tiny subset of the full grammar. The ambiguity is that '//' can be both a _cmdargv and a _WSCOMM.

This fails in lark 0.8.5 and 0.8.8.

**Comment by erezsh** [comment]
I think this error has been solved by now. Running this code on `master` doesn't produce any error.

Any chance you can check?

**Comment by jnwatson** [comment]
Just checked. Looks good! Thanks again for your hard work!
