### ISSUE TITLE
Stochastic error on reconstruction

### ISSUE THREAD

**Issue by julienmalard** [lark-parser/lark#611]
**Describe the bug**
Reconstruction with the grammar below gives (in alternating manner) either the correct response, or else an Infinite recursion error. (The parsing step always works fine.) I have tried debugging, etc. and was unable to pinpoint a precise cause, though I think it may be because the ForestVisitor in Earley occasionally gives a PackedNode with left and right `None, (atom, 0, 2, -inf)` instead of `(power ::= atom* power, 0, 1, -inf), (power, 1, 2, -inf)`.

```python
test = """2 ** 4"""
grammar = r"""
start: power

?power: atom ["**" power]

?atom: NUMBER
     | "(" power ")"
"""
parser = Lark(grammar, parser='lalr', maybe_placeholders=False, **kwargs)
tree = parser.parse(code)
new = Reconstructor(parser).reconstruct(tree)
```

Full traceback for reference:
```
Error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Users/julienmalard/PycharmProjects/lark/tests/test_reconstructor.py", line 179, in test_jenesaistoujourspasquoi
    self.assert_reconstruct(grammar, test)
  File "/Users/julienmalard/PycharmProjects/lark/tests/test_reconstructor.py", line 27, in assert_reconstruct
    new = Reconstructor(parser).reconstruct(tree)
  File "/Users/julienmalard/PycharmProjects/lark/lark/reconstruct.py", line 199, in reconstruct
    for item in x:
  File "/Users/julienmalard/PycharmProjects/lark/lark/reconstruct.py", line 187, in _reconstruct
    for x in self._reconstruct(item):
  File "/Users/julienmalard/PycharmProjects/lark/lark/reconstruct.py", line 182, in _reconstruct
    unreduced_tree = parser.parse(tree.children, tree.data)   # find a full derivation
  File "/Users/julienmalard/PycharmProjects/lark/lark/parsers/earley.py", line 320, in parse
    return forest_tree_visitor.visit(solutions[0])
  File "/Users/julienmalard/PycharmProjects/lark/lark/parsers/earley_forest.py", line 282, in visit
    return super(ForestToTreeVisitor, self).visit(root)
  File "/Users/julienmalard/PycharmProjects/lark/lark/parsers/earley_forest.py", line 199, in visit
    raise ParseError("Infinite recursion in grammar, in rule '%s'!" % next_node.s.name)
lark.exceptions.ParseError: Infinite recursion in grammar, in rule 'power'!
```

**Comment by erezsh** [comment]
Just curious, what makes you say it's stochastic?

**Comment by julienmalard** [comment]
Ah! I meant that approximately 50% of the time I run the script, all goes well, and 50% of the time, it errors. With more exponents (e.g., "3 ** 2 ** 1 ** 2 ** 3 ** 4 ** 5"), it seems to error more often.

**Comment by erezsh** [comment]
Does the latest PR solve this? Or is it unrelated?

**Comment by julienmalard** [comment]
Unfortunately not...this one is in Earley and seems quite tricky.

**Comment by chanicpanic** [comment]
I think this works after #745.

**Comment by erezsh** [comment]
Closing.

@julienmalard If it's still not working, please re-open.
