### ISSUE TITLE
Mutli line comments are not working

### ISSUE THREAD

**Issue by khaled-ek** [lark-parser/lark#682]
I know that there has been an issue in the past about the same topic.

I tried to use the grammars below for multi lines comments, but none of them worked for me.
COMMENT: "/*" /(.|\\n|\\r)+/ "*/"
COMMENT: "/*" /(.|\n|\r)+/ "*/"

I store the grammar in a file as a raw string (r""" grammar """) then I read the file and pass the content to lark

s = f.read()
algorithmCode_parser = Lark(grammars.grammar, start='start', propagate_positions=True)
tree = algorithmCode_parser.parse(s)

Using the COMMENT: "/*" /(.|\\n|\\r)+/ "*/" causes the following error

Traceback (most recent call last):
File ".\main.py", line 6, in
ComplainceChecker.read_model_description(sys.argv[1])
File "C:\projects\EMPHYSIS\algorithmCode.complianceChecker\ComplainceChecker.py", line 315, in read_model_description
tree = algorithmCode_parser.parse(s)
File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\lark.py", line 333, in parse
return self.parser.parse(text, start=start)
File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\parser_frontends.py", line 194, in parse
return self._parse(text, start)
File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\parser_frontends.py", line 54, in _parse
return self.parser.parse(input, start, *args)
File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\parsers\earley.py", line 292, in parse
to_scan = self._parse(stream, columns, to_scan, start_symbol)
File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\parsers\xearley.py", line 138, in _parse
to_scan = scan(i, to_scan)
File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\parsers\xearley.py", line 115, in scan
raise UnexpectedCharacters(stream, i, text_line, text_column, {item.expect.name for item in to_scan}, set(to_scan))
lark.exceptions.UnexpectedCharacters: No terminal defined for '/' at line 1 col 1

/*
^

Expecting: {'BLOCK'}

The COMMENT: "/*" /(.|\n|\r)+/ "*/"  produces the following error:

Traceback (most recent call last):
File ".\main.py", line 6, in <module>
    ComplainceChecker.read_model_description(sys.argv[1])
File "C:\projects\EMPHYSIS\algorithmCode.complianceChecker\ComplainceChecker.py", line 315, in read_model_description
    tree = algorithmCode_parser.parse(s)
File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\lark.py", line 333, in parse
    return self.parser.parse(text, start=start)
File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\parser_frontends.py", line 194, in parse
    return self._parse(text, start)
File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\parsers\earley.py", line 292, in parse
    to_scan = self._parse(stream, columns, to_scan, start_symbol)
File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\parsers\xearley.py", line 138, in _parse
    to_scan = scan(i, to_scan)
File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\parsers\xearley.py", line 115, in scan
    raise UnexpectedCharacters(stream, i, text_line, text_column, {item.expect.name for item in to_scan}, set(to_scan))
lark.exceptions.UnexpectedCharacters: No terminal defined for 'm' at line 99 col 2

        method DoStep
 ^

Expecting: {'BLOCK'}

Any help will be much appreciated.

Best regards,
Khaled

**Comment by khaled-ek** [comment]
Sorry the two comment rules which I used are shown in the attached (in the same order), they do not appear correctly when I try to edit them.


![image](https://user-images.githubusercontent.com/10619141/92389013-83be0900-f118-11ea-9950-283533c21236.png)
![Comment_rules](https://user-images.githubusercontent.com/10619141/92389120-c2ec5a00-f118-11ea-8872-ced3a422366a.png)

**Comment by erezsh** [comment]
Try running this code:

```python
from lark import Lark

p = Lark(r"""
start: WORD+

WORD: /\w+/
ML_COMMENT: "/*" /.*?/s "*/"
%ignore ML_COMMENT
%ignore /\s/s
""")


t = p.parse("""
This is a text /*
   comment
   */
Some more text
/* ok */
/*
comments
*/
More text

""")

print(t.pretty())
```

**Comment by khaled-ek** [comment]
Thank you for your response, I got the following error message when running the suggested code:


raceback (most recent call last):
  File ".\test.py", line 3, in <module>
    p = Lark(r"""
  File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\lark.py", line 207, in __init__
    self.terminals, self.rules, self.ignore_tokens = self.grammar.compile(self.options.start)
  File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\load_grammar.py", line 467, in compile
    terminals = [TerminalDef(name, transformer.transform( term_tree ), priority)
  File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\load_grammar.py", line 467, in <listcomp>
    terminals = [TerminalDef(name, transformer.transform( term_tree ), priority)
  File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\visitors.py", line 138, in transform
    tree = t.transform(tree)
  File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\visitors.py", line 105, in transform
    return self._transform_tree(tree)
  File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\visitors.py", line 101, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\visitors.py", line 92, in _transform_children
    yield self._transform_tree(c)
  File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\visitors.py", line 102, in _transform_tree
    return self._call_userfunc(tree, children)
  File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\visitors.py", line 68, in _call_userfunc
    return f(children)
  File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\load_grammar.py", line 394, in expansion
    raise GrammarError("Lark doesn't support joining terminals with conflicting flags!")
lark.exceptions.GrammarError: Lark doesn't support joining terminals with conflicting flags!

**Comment by erezsh** [comment]
You are probably using an old version of Lark. Upgrade it (to `9.0`) and try again.

**Comment by khaled-ek** [comment]
This is the result of pip list 
![pip-list](https://user-images.githubusercontent.com/10619141/92460672-84ae7380-f1c8-11ea-9cfb-eaf4dec1a51f.png)

**Comment by erezsh** [comment]
Okay, try this code instead:

```python
from lark import Lark

p = Lark(r"""
start: WORD+

WORD: /\w+/
ML_COMMENT: "/*"s /.*?/s "*/"s
%ignore ML_COMMENT
%ignore /\s/s
""")


t = p.parse("""
This is a text /*
   comment
   */
Some more text
/* ok */
/*
comments
*/
More text

""")

print(t.pretty())
```

**Comment by khaled-ek** [comment]
Still does not work, I got the following error:

Traceback (most recent call last):
  File ".\test.py", line 3, in <module>
    p = Lark(r"""
  File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\lark.py", line 246, in __init__
    self.grammar = load_grammar(grammar, self.source, self.re)
  File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\load_grammar.py", line 947, in load_grammar
    return GrammarLoader(re_).load_grammar(grammar, source)
  File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\load_grammar.py", line 906, in load_grammar
    resolve_term_references(term_defs)
  File "C:\Users\khaled\AppData\Local\Programs\Python\Python38-32\lib\site-packages\lark\load_grammar.py", line 706, in resolve_term_references
    raise GrammarError("Rules aren't allowed inside terminals (%s in %s)" % (item, name))
lark.exceptions.GrammarError: Rules aren't allowed inside terminals (s in ML_COMMENT)

**Comment by erezsh** [comment]
Sorry, that one was my bad. Try this:

```python
from lark import Lark

p = Lark(r"""
start: WORD+

WORD: /\w+/
ML_COMMENT: /\/\*.*?\*\//s
%ignore ML_COMMENT
%ignore /\s/s
""")


t = p.parse("""
This is a text /*
   comment
   */
Some more text
/* ok */
/*
comments
*/
More text

""")

print(t.pretty())
```

**Comment by khaled-ek** [comment]
It works now, thank you
