### ISSUE TITLE
line number on rule

### ISSUE THREAD

**Issue by kamadorueda** [lark-parser/lark#687]
**What is your question?**

I have a grammar like this one, for JSON:

```
    ?start: value

    ?value: object
            | array
            | string
            | SIGNED_NUMBER      -> number
            | "true"             -> true
            | "false"            -> false
            | "null"             -> null

    array  : "[" [value ("," value)*] "]"
    object : "{" [pair ("," pair)*] "}"
    pair   : string ":" value

    string : ESCAPED_STRING

    %import common.ESCAPED_STRING
    %import common.SIGNED_NUMBER
    %import common.WS

    %ignore WS
```

if I do this on a transformer:

```
    @staticmethod
    @lark.v_args(inline=True)
    def string(token: lark.Token) -> frozendict:
        return frozendict({
            'column': token.column,
            'item': ast.literal_eval(token),
            'line': token.line
        })
```

I can get line and column numbers

however, in array, or object rules the `tree.meta.line` (or `tree.line`) attributes are empty (and raise an error)

```
    @staticmethod
    @lark.v_args(tree=True)
    def array(tree: lark.Tree) -> frozendict:
```

I would like to be able to get the line number of such properties

Thanks in advance!

**Comment by MegaIng** [comment]
These kind of questions are better asked over at the [gitter chat](https://gitter.im/lark-parser/Lobby).

Also, please read the docs before asking: https://lark-parser.readthedocs.io/en/latest/classes.html?highlight=meta#lark.Tree
clearly states that `meta` is only filled when `propagate_positions` is set to true in the constructor. (so pass `propagate_positions=True` where ever you are creating your Lark instance. This will lead to a slowdown)

**Comment by kamadorueda** [comment]
I'm already doing it, sir:

![image](https://user-images.githubusercontent.com/47480384/93144801-783a8700-f6b0-11ea-940e-101df8c3581f.png)

I've read the docs and it actually works for `number` but it does not for `array`, the code is something like this:

```
GRAMMAR = r"""
    ?start: value

    ?value: object
            | array
            | string
            | SIGNED_NUMBER      -> number
            | "true"             -> true
            | "false"            -> false
            | "null"             -> null

    array  : "[" [value ("," value)*] "]"
    object : "{" [pair ("," pair)*] "}"
    pair   : string ":" value

    string : ESCAPED_STRING

    %import common.ESCAPED_STRING
    %import common.SIGNED_NUMBER
    %import common.WS

    %ignore WS
"""

class Builder(lark.Transformer[frozendict]):

    pair = tuple
    object = frozendict

    @staticmethod
    @lark.v_args(inline=True)
    def string(token: lark.Token) -> frozendict:
        return frozendict({
            'column': token.column,
            'item': ast.literal_eval(token),
            'line': token.line
        })

    @staticmethod
    @lark.v_args(inline=True)
    def number(token: lark.Token) -> frozendict:
        return frozendict({
            'column': token.column,
            'item': ast.literal_eval(token),
            'line': token.line,
        })

    @staticmethod
    @lark.v_args(tree=True)
    def array(tree: lark.Tree) -> frozendict:
        return frozendict({
            'column': 0,
            'item': tuple(tree.children),
            'line': 0,
        })


    json_parser = lark.Lark(
        grammar=GRAMMAR,
        parser='lalr',
        lexer='standard',
        propagate_positions=True,
        maybe_placeholders=False,
        transformer=Builder(),
    )

    json_parser.parse(stream)
```

**Comment by kamadorueda** [comment]
if it helps, the real code is here:

https://gitlab.com/fluidattacks/product/-/blob/master/skims/skims/parse_json/__init__.py

I'm willing to make a pull request (in case it's a bug in lark-parser) if someone points me in the solution direction

**Comment by erezsh** [comment]
@kamadorueda Please provide a minimal example, that when run, exhibits the issue you're referring to.

Also, try parsing without the `transformer=...` keyword, and transforming the result, and see if that helps.

**Comment by kamadorueda** [comment]
Hi, here is a script that reproduces the error:

Using:  `propagate_positions=True`, the lark.Tree object does not contain the line number in the meta property, seems it's an issue in the transformer only

```
# Standard library
import ast
from typing import (
    Optional,
)

# Third party libraries
from frozendict import (  # https://pypi.org/project/frozendict/
    frozendict
)
import lark


# Constants
GRAMMAR = r"""
    ?start: value

    ?value: object
            | array
            | string
            | SIGNED_NUMBER      -> number
            | "false"
            | "true"
            | "null"

    array  : "[" [value ("," value)*] "]"
    object : "{" [pair ("," pair)*] "}"
    pair   : string ":" value

    string : ESCAPED_STRING

    %import common.ESCAPED_STRING
    %import common.SIGNED_NUMBER
    %import common.WS

    %ignore WS
"""


def loads(
    stream: str,
    *,
    default: Optional[frozendict] = None,
) -> frozendict:
    json_parser = lark.Lark(
        grammar=GRAMMAR,
        parser='lalr',
        lexer='standard',
        propagate_positions=True,
        maybe_placeholders=False,
        transformer=Builder(),
    )

    try:
        return json_parser.parse(stream)
    except lark.exceptions.LarkError:
        if default is None:
            raise

        return default


class Builder(lark.Transformer[frozendict]):

    # I can get the line number of a token
    @staticmethod
    @lark.v_args(inline=True)
    def string(token: lark.Token) -> frozendict:
        return frozendict({
            'column': token.column,
            'item': ast.literal_eval(token),
            'line': token.line
        })

    # I cant get the line number of a tree
    @staticmethod
    @lark.v_args(tree=True)
    def array(tree: lark.Tree) -> frozendict:
        print(tree.line)
        return frozendict({
            'column': 0,
            'item': tuple(tree.children),
            'line': 0,
        })

    pair = tuple
    object = frozendict


print(loads('{ "array": [1] }'))

# Traceback (most recent call last):
#   File "/home/kamado/Documents/fluidattacks/product/skims/script.py", line 95, in <module>
#     print(loads('{ "array": [1] }'))
#   File "/home/kamado/Documents/fluidattacks/product/skims/script.py", line 55, in loads
#     return json_parser.parse(stream)
#   File "/home/kamado/Documents/fluidattacks/product/skims/.venv/lib/python3.8/site-packages/lark/lark.py", line 391, in parse
#     return self.parser.parse(text, start=start)
#   File "/home/kamado/Documents/fluidattacks/product/skims/.venv/lib/python3.8/site-packages/lark/parser_frontends.py", line 89, in parse
#     return self._parse(token_stream, start)
#   File "/home/kamado/Documents/fluidattacks/product/skims/.venv/lib/python3.8/site-packages/lark/parser_frontends.py", line 53, in _parse
#     return self.parser.parse(input, start, *args)
#   File "/home/kamado/Documents/fluidattacks/product/skims/.venv/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 36, in parse
#     return self.parser.parse(*args)
#   File "/home/kamado/Documents/fluidattacks/product/skims/.venv/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 98, in parse
#     reduce(arg)
#   File "/home/kamado/Documents/fluidattacks/product/skims/.venv/lib/python3.8/site-packages/lark/parsers/lalr_parser.py", line 78, in reduce
#     value = self.callbacks[rule](s)
#   File "/home/kamado/Documents/fluidattacks/product/skims/.venv/lib/python3.8/site-packages/lark/parse_tree_builder.py", line 28, in __call__
#     res = self.node_builder(children)
#   File "/home/kamado/Documents/fluidattacks/product/skims/.venv/lib/python3.8/site-packages/lark/parse_tree_builder.py", line 127, in __call__
#     return self.node_builder(filtered)
#   File "/home/kamado/Documents/fluidattacks/product/skims/.venv/lib/python3.8/site-packages/lark/parse_tree_builder.py", line 217, in f
#     return wrapper(func, name, children, None)
#   File "/home/kamado/Documents/fluidattacks/product/skims/.venv/lib/python3.8/site-packages/lark/visitors.py", line 351, in _vargs_tree
#     return f(Tree(data, children, meta))
#   File "/home/kamado/Documents/fluidattacks/product/skims/.venv/lib/python3.8/site-packages/lark/visitors.py", line 329, in f
#     return _f(self, *args, **kwargs)
#   File "/home/kamado/Documents/fluidattacks/product/skims/script.py", line 87, in array
#     print(tree.line)
#   File "/home/kamado/Documents/fluidattacks/product/skims/.venv/lib/python3.8/site-packages/lark/tree.py", line 120, in line
#     return self.meta.line
# AttributeError: 'Meta' object has no attribute 'line'
```

**Comment by kamadorueda** [comment]
@erezsh, if I remove the transformer it works!

```
x = loads("""{
    "array":
    [
        1
    ]
}
""")
print(x.children[0].children[1].line)

# 3
```

**Comment by MegaIng** [comment]
This is not a minimal example. We want to test your code easy and fast, and potential create a test from it. For you code, we have to install an third party package.

But anyway, the problem is that there is a reason it is named `propagate_position`. It doesn't actually save the postions at the parsing step, but adds the meta information in a post-processing step. This adds an overhead, which is why it is deactivated by default.

This meta information is only propagated from/added to Tree/Token objects, which your `frozendict` is not.

You are in general kinda defeating the point of the direct transformer parameter, since it core purpose is to not build a Tree object, but you still tell it to build one. I would suggest just using the transformer after the fact on the complete tree.

**Comment by kamadorueda** [comment]
I think that removing the transformer and working on the raw tree is enough for the purpose I need

Sorry if I caused some inconvenience and thanks for your time!

**Comment by erezsh** [comment]
No worries. This happens because `propagate_positions` uses the meta information from the children nodes to calculate the meta for the current node (which is also why empty rules don't have position information).

When you use the `transformer=` option, you are essentially replacing the tree creation process, which means the object you return must have the meta property in order for the propagation to work.

**Comment by erezsh** [comment]
P.S. I highly recommend to use the default lexer, and not the `standard`

**Comment by MegaIng** [comment]
@erezsh Slight correction: Just having an `meta` attribute actually doesn't work, it needs to be an instance of either Token or Tree. It might be worth considering to change this though to support custom AST generation with meta information.

**Comment by erezsh** [comment]
You're right. It has to subclass one of them to work.
