### ISSUE TITLE
I can't create a parser from my grammar

### ISSUE THREAD

**Issue by joepalermo** [lark-parser/lark#724]
**What is your question?**

I can't create a parser from my grammar. I would appreciate any help debugging my grammar.

Here's the traceback:

```
Traceback (most recent call last):
  File "/Users/jpalermo/.conda/envs/mm_for_gpt/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 60, in get_action
    return states[state][token.type]
KeyError: '_RPAR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jpalermo/workspace/math/hol-rainbow/metamath_preprocessing/parse_expressions.py", line 36, in <module>
    parser = Lark(lark_grammar, parser='lalr', debug=True)  # possible values: ('earley', 'lalr', 'cyk', None)
  File "/Users/jpalermo/.conda/envs/mm_for_gpt/lib/python3.7/site-packages/lark/lark.py", line 270, in __init__
    self.grammar = load_grammar(grammar, self.source, re_module)
  File "/Users/jpalermo/.conda/envs/mm_for_gpt/lib/python3.7/site-packages/lark/load_grammar.py", line 985, in load_grammar
    return GrammarLoader(re_).load_grammar(grammar, source)
  File "/Users/jpalermo/.conda/envs/mm_for_gpt/lib/python3.7/site-packages/lark/load_grammar.py", line 824, in load_grammar
    tree = self.canonize_tree.transform( self.parser.parse(grammar_text+'\n') )
  File "/Users/jpalermo/.conda/envs/mm_for_gpt/lib/python3.7/site-packages/lark/parser_frontends.py", line 108, in parse
    return self._parse(token_stream, start)
  File "/Users/jpalermo/.conda/envs/mm_for_gpt/lib/python3.7/site-packages/lark/parser_frontends.py", line 58, in _parse
    return self.parser.parse(input, start, *args)
  File "/Users/jpalermo/.conda/envs/mm_for_gpt/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 36, in parse
    return self.parser.parse(*args)
  File "/Users/jpalermo/.conda/envs/mm_for_gpt/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 89, in parse
    action, arg = get_action(token)
  File "/Users/jpalermo/.conda/envs/mm_for_gpt/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 67, in get_action
    raise UnexpectedToken(token, expected, state=state, puppet=puppet)
lark.exceptions.UnexpectedToken: Unexpected token Token('_RPAR', ')') at line 2, column 106.
Expected one of: 
	* _OR
	* _NL
```

I'm reading my grammar in from a text file and then invoking Lark as follows: 

`parser = Lark(lark_grammar, parser='lalr', debug=True)`

Here's the grammar (note that it has about 1500 production rules):

[lark_grammar.txt](https://github.com/lark-parser/lark/files/5394258/lark_grammar.txt)

**Comment by MegaIng** [comment]
`"/\"` is not a valid string literal. It has an escaped `"`, meaning the actual string literals continues a bit. Somehow your grammar is designed in a way that it doesn't break the lexer, but only the parser. A syntax highlighter would help there.

Also, these kinds of questions are better over at the [gitter chat](gitter.im/lark-parser/Lobby).

**Comment by erezsh** [comment]
As @MegaIng said, you should use "/\\" instead.

**Comment by MegaIng** [comment]
@erezsh that is what he is using. I assume you mean `"/\\"`

**Comment by erezsh** [comment]
Whoops, I forgot to quote it.

**Comment by joepalermo** [comment]
Thanks. That resolved it.

**Comment by joepalermo** [comment]
@MegaIng I can't access that link

**Comment by erezsh** [comment]
https://gitter.im/lark-parser/Lobby
