### ISSUE TITLE
Error while parsing multiple statements in Lark.

### ISSUE THREAD

**Issue by AbooMinister25** [lark-parser/lark#744]
I'm making a programming language using lark, and I can't figure out how to parse multiple statements from a file. I'm trying to parse 
```py
print("HI");
print("HI");
```
but I get
 ```py
PS E:\ParserAndLexer> & C:/Python38/python.exe e:/ParserAndLexer/lite/main.py
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\lark\lexer.py", line 416, in lex
    for x in l.lex(stream, self.root_lexer.newline_types, self.root_lexer.ignore_types):
  File "C:\Python38\lib\site-packages\lark\lexer.py", line 200, in lex
    raise UnexpectedCharacters(stream, line_ctr.char_pos, line_ctr.line, line_ctr.column, allowed=allowed, state=self.state, token_history=last_token and [last_token])
lark.exceptions.UnexpectedCharacters: No terminal defined for 'p' at line 2 col 1

print("HI");
^

Expecting: {'RBRACE'}

Previous tokens: Token('SEMICOLON', ';')


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:/ParserAndLexer/lite/main.py", line 21, in <module>
    print(lite_parser(lite_code))
  File "C:\Python38\lib\site-packages\lark\lark.py", line 464, in parse
    return self.parser.parse(text, start=start)
  File "C:\Python38\lib\site-packages\lark\parser_frontends.py", line 148, in parse
    return self._parse(token_stream, start, set_parser_state)
  File "C:\Python38\lib\site-packages\lark\parser_frontends.py", line 63, in _parse
    return self.parser.parse(input, start, *args)
  File "C:\Python38\lib\site-packages\lark\parsers\lalr_parser.py", line 35, in parse
    return self.parser.parse(*args)
  File "C:\Python38\lib\site-packages\lark\parsers\lalr_parser.py", line 86, in parse
    for token in stream:
  File "C:\Python38\lib\site-packages\lark\indenter.py", line 32, in _process
    for token in stream:
  File "C:\Python38\lib\site-packages\lark\lexer.py", line 431, in lex
    raise UnexpectedToken(t, e.allowed, state=e.state)
lark.exceptions.UnexpectedToken: Unexpected token Token('NAME', 'print') at line 2, column 1.
Expected one of:
        * RBRACE
```
Heres my `.lark` file
```
?start: expr
      | statement
      | var
      | bool
      | condition
      | if

?expr: STRING            -> string
     | NUMBER            -> number
     | NUMBER "+" NUMBER -> add
     | NUMBER "-" NUMBER -> sub
     | NUMBER "*" NUMBER -> mul
     | NUMBER "/" NUMBER -> div
     | STRING "+" STRING -> str_add

?bool: TRUE              -> true
     | FALSE             -> false

?condition: expr "==" bool -> bool_comparison
          | expr "==" expr -> expr_comparison

?statement: "print" "(" expr ")" ";"  -> print_statement
          | "input" "(" expr ")" ";"  -> input_statement

?if : "if" condition "{" statement "}" -> if_statement

?var: NAME "=" expr      -> assign_var
    | NAME              -> get_var


TRUE: "true"
FALSE: "false"


%import common.ESCAPED_STRING -> STRING 
%import common.NUMBER
%import common.CNAME -> NAME
%declare _INDENT _DEDENT
%import common.WS_INLINE
%ignore WS_INLINE
%import common.NEWLINE -> _NL
%ignore _NL
```

Any idea why this is happening? I'm ignoring newlines, so I can't see why its not working. Help would be appreciated, Thanks!

**Comment by erezsh** [comment]
You have nothing to support multiple statements. Try `start: statement*`

**Comment by AbooMinister25** [comment]
Ohh, ok, thanks! I'll try that

**Comment by AbooMinister25** [comment]
It worked, but now its returning `Tree('start', ['HI', 'HI'])`, and not the transformed version

**Comment by AbooMinister25** [comment]
In my transformer I have 
```py
def print_statement(self, value):
      value = str(value).strip('"')
      return value
```
and if I change `return` to `print` like
```py
def print_statement(self, value):
      value = str(value).strip('"')
      print(value)
``` 
I get 
```py
HI
HI
Tree('start', [None, None])
```

**Comment by erezsh** [comment]
What is the problem? Everything seems to be working as it should.

**Comment by AbooMinister25** [comment]
I'm not getting an output, its giving me the correct output if I have one expression, but if I have multiple, its returning a Tree.

**Comment by erezsh** [comment]
Sorry, I didn't see your reply. That's what the `?` before the rule name does.
