### ISSUE TITLE
Use "[" or "]" in regex

### ISSUE THREAD

**Issue by ilius** [lark-parser/lark#757]
How can I use `[`, `]` and `/` characters in regex?
I tried escaping them with `\` but it's not working.
`TEXT: /[^\[\]/]+/m`

```
grammar = r"""?start: text

text: [elem*]

elem: TEXT
	| bold
	| italic
	| color
	| para
	| m1
	| m2

TEXT: /[^\[\]/]+/m
bold: "[b]"i text "[/b]"i
italic: "[i]"i text "[/i]"i
color_open: "[c]"i | ("[c "i /[a-z]+/i "]")
color: color_open text "[/c]"i
para: "[p]"i text "[/p]"i
m1: "[m1]"i text "[/m1]"i
m2: "[m2]"i text "[/m2]"i

"""
```

Exception:

```
Traceback (most recent call last):
  File "./demo.py", line 57, in <module>
    parser = Lark(grammar, parser='lalr', transformer=DSLTree())
  File "/usr/local/lib/python3.8/dist-packages/lark_parser-0.11.0rc1-py3.8.egg/lark/lark.py", line 299, in __init__
    self.grammar = load_grammar(grammar, self.source_path, self.options.import_paths, self.options.keep_all_tokens)
  File "/usr/local/lib/python3.8/dist-packages/lark_parser-0.11.0rc1-py3.8.egg/lark/load_grammar.py", line 1061, in load_grammar
    return GrammarLoader(global_keep_all_tokens).load_grammar(grammar, source, import_paths)
  File "/usr/local/lib/python3.8/dist-packages/lark_parser-0.11.0rc1-py3.8.egg/lark/load_grammar.py", line 895, in load_grammar
    tree = self.canonize_tree.transform(self.parser.parse(grammar_text+'\n'))
  File "/usr/local/lib/python3.8/dist-packages/lark_parser-0.11.0rc1-py3.8.egg/lark/parser_frontends.py", line 138, in parse
    return self._parse(start, self.make_lexer(text))
  File "/usr/local/lib/python3.8/dist-packages/lark_parser-0.11.0rc1-py3.8.egg/lark/parser_frontends.py", line 73, in _parse
    return self.parser.parse(input, start, *args)
  File "/usr/local/lib/python3.8/dist-packages/lark_parser-0.11.0rc1-py3.8.egg/lark/parsers/lalr_parser.py", line 35, in parse
    return self.parser.parse(*args)
  File "/usr/local/lib/python3.8/dist-packages/lark_parser-0.11.0rc1-py3.8.egg/lark/parsers/lalr_parser.py", line 129, in parse
    return self.parse_from_state(parser_state)
  File "/usr/local/lib/python3.8/dist-packages/lark_parser-0.11.0rc1-py3.8.egg/lark/parsers/lalr_parser.py", line 145, in parse_from_state
    raise e
  File "/usr/local/lib/python3.8/dist-packages/lark_parser-0.11.0rc1-py3.8.egg/lark/parsers/lalr_parser.py", line 136, in parse_from_state
    state.feed_token(token)
  File "/usr/local/lib/python3.8/dist-packages/lark_parser-0.11.0rc1-py3.8.egg/lark/parsers/lalr_parser.py", line 89, in feed_token
    raise UnexpectedToken(token, expected, state=state, puppet=None)
lark.exceptions.UnexpectedToken: Unexpected token Token('_RBRA', ']') at line 13, column 17.
```

**Comment by ilius** [comment]
Sorry, my mistake, forgot to escape `/`.
The error `Unexpected token Token('_RBRA', ']')` was a bit misleading I guess.

**Comment by ThatXliner** [comment]
Wonder if better regex error messages would help

**Comment by ilius** [comment]
Here the error is not from regex.
The regex is enclosed by `/`, so `/` itself needs to be escaped.

**Comment by ilius** [comment]
Actually the error totally makes sense from lexing point of view.
But it can still be improved to be more user-friendly, and address common mistakes like this.

**Comment by ThatXliner** [comment]
We're all so used to python's `r"r[eg]+x"`es

**Comment by erezsh** [comment]
Yes, making good errors is hard! For example, this token:

    /fds/a b c d/

Is completely legal until the last /. So there is no hint to the parser that this is an escaping issue. It might as well be that it was meant to be a comment, or a `?` but you forgot the shift. It's really hard to guess when the user intended to happen. It's much easier to tell him what went wrong.

**Comment by MegaIng** [comment]
But it might be possible to add a decent entry to [`GrammarLoader.ERRORS`](https://github.com/lark-parser/lark/blob/4246477aaea7aa9a4c6803ec7f3c8589228e5672/lark/load_grammar.py#L836) for forgetting to escape.
But that might be really hard

**Comment by ilius** [comment]
I agree.
JavaScript-style regex is hard to deal with.
I like Parsimonious's regexp (`~"[a-z]+"` or `~r"[a-z]+"`)
(Although it uses `/` instead of `|` = OR which doesn't make much sense to me)

**Comment by ilius** [comment]
I wrote [this simpler parser](https://github.com/ilius/repassgen) in Go, and I kind of hacked the lexer in several places to help user understand the mistake when it's easy to detect, like [this mistake](https://github.com/ilius/repassgen/blob/master/lex_repeat.go#L28) (that I made myself several times!)
