### ISSUE TITLE
How would I ignore errors in lark and add custom ones?

### ISSUE THREAD

**Issue by AbooMinister25** [lark-parser/lark#764]
I'm parsing a python like programming language using lark, and I was wondering if I could implement custom error messages. For example, if I parse
```
print("Hello")
``` 
I get 
```py
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\lark\parsers\lalr_parser.py", line 59, in get_action
    return states[state][token.type]
KeyError: '$END'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:/ParserAndLexer/lite/lite_transformer.py", line 131, in <module>
    tree = parser.parse(lite_code)
  File "C:\Python38\lib\site-packages\lark\lark.py", line 464, in parse
    return self.parser.parse(text, start=start)
  File "C:\Python38\lib\site-packages\lark\parser_frontends.py", line 148, in parse
    return self._parse(token_stream, start, set_parser_state)
  File "C:\Python38\lib\site-packages\lark\parser_frontends.py", line 63, in _parse
    return self.parser.parse(input, start, *args)
  File "C:\Python38\lib\site-packages\lark\parsers\lalr_parser.py", line 35, in parse
    return self.parser.parse(*args)
  File "C:\Python38\lib\site-packages\lark\parsers\lalr_parser.py", line 111, in parse
    _action, arg = get_action(token)
  File "C:\Python38\lib\site-packages\lark\parsers\lalr_parser.py", line 66, in get_action
    raise UnexpectedToken(token, expected, state=state, puppet=puppet)
lark.exceptions.UnexpectedToken: Unexpected token Token('$END', '') at line 1, column 11.
Expected one of:
        * SEMICOLON
```
But instead of this, could I instead have my own error message that states the line and column? I looked into `propagate_positions`, but I don't really know where to go from there. I'm also trying to parse a `try/catch` statement, but that won't work, for example, if I have this
```
try {
  print("HI")
}
catch {
  print("No semicolon");
}
```
I still get the missing semicolon error.  This is how I have it in my `.lark` file
```
         | "try" block "catch" block     -> try_catch
```
And heres my transformer
```py
    def try_catch(self, try_block, catch_block):
        return TryCatch(try_block, catch_block)
```
And heres the AST for that
```py
class TryCatch():
    def __init__(self, try_block, except_block):
        self.try_block = try_block
        self.except_block = except_block
    
    def eval(self):
        try:
            self.try_block.eval()
        except:
            self.except_block.eval()
```
But this won't work. Help would be appreciated, thanks!

**Comment by erezsh** [comment]
If you catch the lark exception, you can use it to get all the relevant information. Then just raise your own error, reporting whatever you like.

See here: https://lark-parser.readthedocs.io/en/latest/classes.html#unexpectedinput

**Comment by AbooMinister25** [comment]
Yeah, but how would I get the line and column where the error is at? Im doing
```py
    try:
        tree = parser.parse(lite_code)
    except exceptions.UnexpectedToken:
        ...
``` 
But this wont show the lines

**Comment by AbooMinister25** [comment]
Oh wait, I see something called `get_context()`, would this work?

**Comment by erezsh** [comment]
It might, depending on what you need.

If you run `dir()` on the exception, you'll see everything available to you.

**Comment by AbooMinister25** [comment]
Alright, thanks
