### ISSUE TITLE
v0.11.1: Unit test errors

### ISSUE THREAD

**Issue by wiene** [lark-parser/lark#775]
Running the unit tests on lark version 0.11.1 I get the following errors (using Python 3.8 and 3.9):
```
======================================================================
ERROR: test_import_custom_sources (tests.test_parser.tests.test_parser.TestCykStandard)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/test_parser.py", line 1947, in test_import_custom_sources
    p = _Lark(grammar, import_paths=[custom_loader2])
  File "/<<PKGBUILDDIR>>/tests/test_parser.py", line 946, in _Lark
    return Lark(grammar, lexer=lexer_class_or_name, parser=PARSER, propagate_positions=True, **kwargs)
  File "/<<PKGBUILDDIR>>/lark/lark.py", line 300, in __init__
    self.grammar = load_grammar(grammar, self.source_path, self.options.import_paths, self.options.keep_all_tokens)
  File "/<<PKGBUILDDIR>>/lark/load_grammar.py", line 1061, in load_grammar
    return GrammarLoader(global_keep_all_tokens).load_grammar(grammar, source, import_paths)
  File "/<<PKGBUILDDIR>>/lark/load_grammar.py", line 978, in load_grammar
    g = self.import_grammar(grammar_path, base_path=base_path, import_paths=import_paths)
  File "/<<PKGBUILDDIR>>/lark/load_grammar.py", line 886, in import_grammar
    open(grammar_path, encoding='utf8')
FileNotFoundError: [Errno 2] No such file or directory: 'test_relative_import.lark'

======================================================================
ERROR: test_import_custom_sources (tests.test_parser.tests.test_parser.TestEarleyDynamic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/test_parser.py", line 1947, in test_import_custom_sources
    p = _Lark(grammar, import_paths=[custom_loader2])
  File "/<<PKGBUILDDIR>>/tests/test_parser.py", line 946, in _Lark
    return Lark(grammar, lexer=lexer_class_or_name, parser=PARSER, propagate_positions=True, **kwargs)
  File "/<<PKGBUILDDIR>>/lark/lark.py", line 300, in __init__
    self.grammar = load_grammar(grammar, self.source_path, self.options.import_paths, self.options.keep_all_tokens)
  File "/<<PKGBUILDDIR>>/lark/load_grammar.py", line 1061, in load_grammar
    return GrammarLoader(global_keep_all_tokens).load_grammar(grammar, source, import_paths)
  File "/<<PKGBUILDDIR>>/lark/load_grammar.py", line 978, in load_grammar
    g = self.import_grammar(grammar_path, base_path=base_path, import_paths=import_paths)
  File "/<<PKGBUILDDIR>>/lark/load_grammar.py", line 886, in import_grammar
    open(grammar_path, encoding='utf8')
FileNotFoundError: [Errno 2] No such file or directory: 'test_relative_import.lark'

======================================================================
ERROR: test_import_custom_sources (tests.test_parser.tests.test_parser.TestEarleyStandard)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/test_parser.py", line 1947, in test_import_custom_sources
    p = _Lark(grammar, import_paths=[custom_loader2])
  File "/<<PKGBUILDDIR>>/tests/test_parser.py", line 946, in _Lark
    return Lark(grammar, lexer=lexer_class_or_name, parser=PARSER, propagate_positions=True, **kwargs)
  File "/<<PKGBUILDDIR>>/lark/lark.py", line 300, in __init__
    self.grammar = load_grammar(grammar, self.source_path, self.options.import_paths, self.options.keep_all_tokens)
  File "/<<PKGBUILDDIR>>/lark/load_grammar.py", line 1061, in load_grammar
    return GrammarLoader(global_keep_all_tokens).load_grammar(grammar, source, import_paths)
  File "/<<PKGBUILDDIR>>/lark/load_grammar.py", line 978, in load_grammar
    g = self.import_grammar(grammar_path, base_path=base_path, import_paths=import_paths)
  File "/<<PKGBUILDDIR>>/lark/load_grammar.py", line 886, in import_grammar
    open(grammar_path, encoding='utf8')
FileNotFoundError: [Errno 2] No such file or directory: 'test_relative_import.lark'

======================================================================
ERROR: test_import_custom_sources (tests.test_parser.tests.test_parser.TestLalrContextual)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/test_parser.py", line 1947, in test_import_custom_sources
    p = _Lark(grammar, import_paths=[custom_loader2])
  File "/<<PKGBUILDDIR>>/tests/test_parser.py", line 946, in _Lark
    return Lark(grammar, lexer=lexer_class_or_name, parser=PARSER, propagate_positions=True, **kwargs)
  File "/<<PKGBUILDDIR>>/lark/lark.py", line 300, in __init__
    self.grammar = load_grammar(grammar, self.source_path, self.options.import_paths, self.options.keep_all_tokens)
  File "/<<PKGBUILDDIR>>/lark/load_grammar.py", line 1061, in load_grammar
    return GrammarLoader(global_keep_all_tokens).load_grammar(grammar, source, import_paths)
  File "/<<PKGBUILDDIR>>/lark/load_grammar.py", line 978, in load_grammar
    g = self.import_grammar(grammar_path, base_path=base_path, import_paths=import_paths)
  File "/<<PKGBUILDDIR>>/lark/load_grammar.py", line 886, in import_grammar
    open(grammar_path, encoding='utf8')
FileNotFoundError: [Errno 2] No such file or directory: 'test_relative_import.lark'

======================================================================
ERROR: test_import_custom_sources (tests.test_parser.tests.test_parser.TestLalrCustom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/test_parser.py", line 1947, in test_import_custom_sources
    p = _Lark(grammar, import_paths=[custom_loader2])
  File "/<<PKGBUILDDIR>>/tests/test_parser.py", line 946, in _Lark
    return Lark(grammar, lexer=lexer_class_or_name, parser=PARSER, propagate_positions=True, **kwargs)
  File "/<<PKGBUILDDIR>>/lark/lark.py", line 300, in __init__
    self.grammar = load_grammar(grammar, self.source_path, self.options.import_paths, self.options.keep_all_tokens)
  File "/<<PKGBUILDDIR>>/lark/load_grammar.py", line 1061, in load_grammar
    return GrammarLoader(global_keep_all_tokens).load_grammar(grammar, source, import_paths)
  File "/<<PKGBUILDDIR>>/lark/load_grammar.py", line 978, in load_grammar
    g = self.import_grammar(grammar_path, base_path=base_path, import_paths=import_paths)
  File "/<<PKGBUILDDIR>>/lark/load_grammar.py", line 886, in import_grammar
    open(grammar_path, encoding='utf8')
FileNotFoundError: [Errno 2] No such file or directory: 'test_relative_import.lark'

======================================================================
ERROR: test_import_custom_sources (tests.test_parser.tests.test_parser.TestLalrStandard)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/tests/test_parser.py", line 1947, in test_import_custom_sources
    p = _Lark(grammar, import_paths=[custom_loader2])
  File "/<<PKGBUILDDIR>>/tests/test_parser.py", line 946, in _Lark
    return Lark(grammar, lexer=lexer_class_or_name, parser=PARSER, propagate_positions=True, **kwargs)
  File "/<<PKGBUILDDIR>>/lark/lark.py", line 300, in __init__
    self.grammar = load_grammar(grammar, self.source_path, self.options.import_paths, self.options.keep_all_tokens)
  File "/<<PKGBUILDDIR>>/lark/load_grammar.py", line 1061, in load_grammar
    return GrammarLoader(global_keep_all_tokens).load_grammar(grammar, source, import_paths)
  File "/<<PKGBUILDDIR>>/lark/load_grammar.py", line 978, in load_grammar
    g = self.import_grammar(grammar_path, base_path=base_path, import_paths=import_paths)
  File "/<<PKGBUILDDIR>>/lark/load_grammar.py", line 886, in import_grammar
    open(grammar_path, encoding='utf8')
FileNotFoundError: [Errno 2] No such file or directory: 'test_relative_import.lark'

----------------------------------------------------------------------
Ran 687 tests in 36.485s

FAILED (errors=6, skipped=68)
```
It seems the CI tests did not show a similar issue. Do you have any idea what is going wrong here?

**Comment by MegaIng** [comment]
How are you running them?

**Comment by wiene** [comment]
> How are you running them?
```
PYTHONWARNINGS=d python3.9 -m unittest discover -v tests
```

**Comment by MegaIng** [comment]
With `python -m tests` it works. unittest does something else that somehow hurts file finding.

**Comment by ThatXliner** [comment]
Oh ok. I had the same problem when I did `pytest`

**Comment by wiene** [comment]
I investigated the issue using bisection and it turned out that the commit dcde0bc is the first commit that leads to failing unit tests using
```
PYTHONWARNINGS=d python3.9 -m unittest discover -v tests
```

**Comment by MegaIng** [comment]
Yes, but for other reasons.

**Comment by MegaIng** [comment]
A better guess for the breaking commit is 009cc105907987a1afab22b769685eb7c89b0e82. It also changes things that might break the import system, as oppose to the other commit.

**Comment by MegaIng** [comment]
Ok, found the source of the 'bug'. It is just that the tests weren't able to deal with a situation where `__main__` isn't within `tests`. I will create a PR. lucky, the same commit that introduced this problem also contained an easy way to fix this.
