### ISSUE TITLE
`Discard` __default__

### ISSUE THREAD

**Issue by V0idExp** [lark-parser/lark#864]
**Describe the bug**

If `Discard` exception is raised in __default__ method, Lark re-raises it, instead of discarding the matched rule.

**To Reproduce**

```
from lark.visitors import Transformer, Discard
from lark import Lark


class MyTransformer(Transformer):

    def a(self, t):
        return t[0]

    def __default__(self, *args):
        raise Discard


grammar = '''
?start: (a | b)*
a: HELLO
b: WORLD

HELLO: "hello"
WORLD: "world"
'''

tree = Lark(grammar, parser='lalr').parse('helloworld')
tree = MyTransformer().transform(tree)
print(tree.pretty())
```

The code above would fail with:
```
Traceback (most recent call last):
  File "D:\projects\nesquik\.venv\lib\site-packages\lark\visitors.py", line 84, in _call_userfunc
    f = getattr(self, tree.data)
AttributeError: 'MyTransformer' object has no attribute 'start'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\projects\nesquik\src\nesquik\bug.py", line 24, in <module>
    tree = MyTransformer().transform(tree)
  File "D:\projects\nesquik\.venv\lib\site-packages\lark\visitors.py", line 130, in transform
    return self._transform_tree(tree)
  File "D:\projects\nesquik\.venv\lib\site-packages\lark\visitors.py", line 126, in _transform_tree
    return self._call_userfunc(tree, children)
  File "D:\projects\nesquik\.venv\lib\site-packages\lark\visitors.py", line 86, in _call_userfunc
    return self.__default__(tree.data, children, tree.meta)
  File "D:\projects\nesquik\src\nesquik\bug.py", line 11, in __default__
    raise Discard
lark.visitors.Discard
```

**Comment by MegaIng** [comment]
This is the expected behavior. You don't have a handler defined for `start`, so `__default__` is called for it. Since `start` is the root of the Tree, we can't remove it from any list.
