### ISSUE TITLE
Newline regex considered as zero length

### ISSUE THREAD

**Issue by jthomme1** [lark-parser/lark#919]
**Describe the bug**
I'm using the Earley parser for parsing with lark.
When using a regular expression consisting of a single newline `\n` (or together with a lookahead in the regex) - e.g. `/\n(?=a)/x` - lark complains that the regular expression is of zero length - which it is not.
Also, the usage of other flags `mliux` does not change this behaviour.

**To Reproduce**
```python
import re
from lark import Lark
GRAMMAR = """start: /\n(?=a)/x"""
parser = Lark(GRAMMAR, ambiguity="resolve", debug=True)
print(parser.parse("\na").pretty())
```

**Error Message**
```
Traceback (most recent call last):                                                                                
  File "min_work_ex.py", line 8, in <module>                                                                      
    parser = Lark(GRAMMAR, ambiguity="resolve", debug=True)                                                       
  File "/home/lol/.local/lib/python3.8/site-packages/lark/lark.py", line 377, in __init__                      
    self.parser = self._build_parser()                                                                            
  File "/home/lol/.local/lib/python3.8/site-packages/lark/lark.py", line 419, in _build_parser                 
    return parser_class(self.lexer_conf, parser_conf, options=self.options)                                       
  File "/home/lol/.local/lib/python3.8/site-packages/lark/parser_frontends.py", line 40, in __call__           
    return ParsingFrontend(lexer_conf, parser_conf, options)                                                      
  File "/home/lol/.local/lib/python3.8/site-packages/lark/parser_frontends.py", line 69, in __init__           
    self.parser = create_parser(lexer_conf, parser_conf, options)                                                 
  File "/home/lol/.local/lib/python3.8/site-packages/lark/parser_frontends.py", line 216, in create_earley_pars
er                                                                                                                
    return f(lexer_conf, parser_conf, options, resolve_ambiguity=resolve_ambiguity, debug=debug, tree_class=tree_c
lass, **extra)                                                                                                    
  File "/home/lol/.local/lib/python3.8/site-packages/lark/parser_frontends.py", line 193, in create_earley_pars
er__dynamic                                                                                                       
    earley_matcher = EarleyRegexpMatcher(lexer_conf)                                                              
  File "/home/lol/.local/lib/python3.8/site-packages/lark/parser_frontends.py", line 182, in __init__          
    raise GrammarError("Dynamic Earley doesn't allow zero-width regexps", t)                                      
lark.exceptions.GrammarError: ("Dynamic Earley doesn't allow zero-width regexps", TerminalDef('__ANON_0', '(?x:\n(
?=a))'))                                                                                                          
```

**Lark version**
lark-parser==0.11.3

**Question**
Is this in any way intended? Or is there a way around this problem?
Thanks in advance for your response :)

**Comment by MegaIng** [comment]
The regex is Zero length. You have the `x` flag, which means that all Whitespace characters are ignored. The escape sequence `\n` will get translate to a newline before being passed to the regex engine. That means that it is ignored. There are two fixes: Don't use the `x` flag, or add another backslash: `\\n`.

**Comment by jthomme1** [comment]
Thank you very much for your fast and helpful response.

**Comment by erezsh** [comment]
Actually, I would recommend a third solution: Escape your grammar with `r`.

```python
GRAMMAR = r"""start: /\n(?=a)/x"""
```

**Comment by MegaIng** [comment]
@erezsh That doesn't work. Is it supposed to?

**Comment by erezsh** [comment]
You're right, and `\\n` doesn't work on its own either. It needs both:

```python
GRAMMAR = r"""start: /\\n(?=a)/x"""
```

**Comment by MegaIng** [comment]
@erezsh That is true (I assumed the grammar came from a file for some reason). I think we discussed this before: Shouldn't regex automatically be treated as if they are in a raw string?

**Comment by erezsh** [comment]
I don't think so, but you're welcome to make the argument. Preferably in a separate issue.
