### ISSUE TITLE
Making a deepcopy of a lark parser throws an error, is this expected?

### ISSUE THREAD

**Issue by brando90** [lark-parser/lark#938]
**Describe the bug**

```
import copy
copy.deepcopy(parser)
Traceback (most recent call last):
  File "/Users/miranda9/.conda/envs/synthesis/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3396, in run_code
    async def run_code(self, code_obj, result=None, *, async_=False):
  File "<ipython-input-3-e99c7bd5e110>", line 1, in <module>
    copy.deepcopy(parser)
  File "/Users/miranda9/.conda/envs/synthesis/lib/python3.9/copy.py", line 128, in deepcopy
    def deepcopy(x, memo=None, _nil=[]):
  File "/Users/miranda9/.conda/envs/synthesis/lib/python3.9/copy.py", line 258, in _reconstruct
    def _reconstruct(x, memo, func, args,
  File "/Users/miranda9/.conda/envs/synthesis/lib/python3.9/copy.py", line 128, in deepcopy
    def deepcopy(x, memo=None, _nil=[]):
  File "/Users/miranda9/.conda/envs/synthesis/lib/python3.9/copy.py", line 226, in _deepcopy_dict
    def _deepcopy_dict(x, memo, deepcopy=deepcopy):
  File "/Users/miranda9/.conda/envs/synthesis/lib/python3.9/copy.py", line 128, in deepcopy
    def deepcopy(x, memo=None, _nil=[]):
  File "/Users/miranda9/.conda/envs/synthesis/lib/python3.9/copy.py", line 258, in _reconstruct
    def _reconstruct(x, memo, func, args,
  File "/Users/miranda9/.conda/envs/synthesis/lib/python3.9/copy.py", line 128, in deepcopy
    def deepcopy(x, memo=None, _nil=[]):
  File "/Users/miranda9/.conda/envs/synthesis/lib/python3.9/copy.py", line 226, in _deepcopy_dict
    def _deepcopy_dict(x, memo, deepcopy=deepcopy):
  File "/Users/miranda9/.conda/envs/synthesis/lib/python3.9/copy.py", line 128, in deepcopy
    def deepcopy(x, memo=None, _nil=[]):
TypeError: cannot pickle 'module' object
```

**To Reproduce**

```
parser1 = Lark('term : \"a\" ', start='term', keep_all_tokens=True)
copy.deepcopy(parser1)
```

perhaps this is an expected bug but surprised me.

**Comment by MegaIng** [comment]
It is kind of a bug. I would have expected it to work, since module objects should be copied in the same way a function is: Not at all, and instead by reference.

**Comment by erezsh** [comment]
Yes, I consider it a bug. I just pushed a fix.
